import {
  createContext,
  useCallback,
  useContext,
  useState,
  type ReactNode,
} from "react";
import { readStoredLang, writeStoredLang } from "@/lib/languageStorage";

export type Lang = "en" | "gr";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Navbar
    "nav.brand": "VALITSA",
    "nav.terms": "Terms & Conditions",
    "nav.daily": "Daily Trips",
    "nav.twoday": "2-Day Trips",
    "nav.multiday": "Multiday Trips",
    "nav.multidayAll": "All multiday trips",
    "nav.multidayDaysOption": "{n}-day trips",
    "nav.multidayAria": "Multiday trips menu",
    "nav.internal": "Domestic Trips",
    "nav.external": "International Trips",
    "nav.contactBtn": "Contact",
    "nav.toggleLanguage": "Toggle language",
    "nav.toggleTheme": "Toggle theme",
    "nav.menu": "Menu",
    "nav.seasonal": "Seasonal",
    "nav.seasonalAria": "Seasonal trips menu",
    "nav.more": "More",
    "nav.moreAria": "More trip categories",
    "archive.seasonal": "Seasonal",
    "archive.seasonalAll": "All trips",

    // Common
    "common.close": "Close",
    "common.scrollUp": "Scroll up",
    "common.scrollUpAria": "Scroll to top",

    // Contact Modal
    "contact.title": "Contact Us",
    "contact.callUs": "Call Us",
    "contact.whatsapp": "WhatsApp",
    "contact.whatsappDesc": "Chat with us instantly",
    "contact.viber": "Viber",
    "contact.viberDesc": "Message us on Viber",
    "contact.sendMessage": "Send a Message",
    "contact.sendMessageDesc": "Fill out the form and we'll get back to you",
    "contact.back": "Back",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.sendFailed": "Failed to send message. Please try again.",
    "contact.sent": "Message Sent!",
    "contact.sentDesc": "We'll get back to you within 24 hours.",

    "validation.required": "This field is required",
    "validation.emailInvalid": "Please enter a valid email address",
    "validation.phoneInvalid": "Please enter a valid phone number",

    // Hero
    "hero.label": "Less routine, more life",
    "hero.title": "Prepare your 'Valitses'",
    "hero.subtitle":
      "Every trip has secret destinations that the traveler doesn't know. -Martin Buber",
    "hero.cta": "View All Our Trips",
    "hero.alt": "Aerial view of a serene tropical coastline",

    // Featured
    "featured.label": "Curated Collections",
    "featured.title": "Featured Escapes",
    "featured.viewAll": "View all trips",

    // Trip Grid
    "grid.label": "Curated Collections",
    "grid.title": "Featured Escapes",
    "grid.all": "All",
    "grid.viewDetails": "View Details",

    // Trip Card Quick Links
    "card.moreDuration": "More {duration} Trips",
    "card.moreType": "More {type} Trips",
    "card.trip": "Trip",
    "card.seasonalFallback": "Seasonal",

    // Trip Detail
    "detail.startingFrom": "Starting from",
    "detail.expressInterest": "Express Your Interest",
    "detail.firstName": "First Name",
    "detail.lastName": "Last Name",
    "detail.email": "Email Address",
    "detail.mobile": "Mobile",
    "detail.message": "Tell us about your preferences...",
    "detail.sendInquiry": "Send Inquiry",
    "detail.sending": "Sending...",
    "detail.sendFailed": "Failed to send inquiry. Please try again.",
    "detail.inquirySent": "Inquiry Sent",
    "detail.inquiryMsg": "We'll be in touch within 24 hours.",
    "detail.description": "Description",
    "detail.tripNotes": "Notes",
    "detail.departureDates": "Departure dates",
    "detail.departureDatesMonthCol": "Month",
    "detail.departureDatesDaysCol": "Days",
    "detail.pricingSegmentsTitle": "Departures and prices",
    "detail.pricingDepartures": "Departures",
    "detail.pricingDepartureCity": "Departure city",
    "detail.pricingHotelCol": "Hotel",
    "detail.pricingDurationCol": "Duration",
    "detail.pricingDoubleCol": "Double",
    "detail.pricingSingleCol": "Single",
    "detail.pricingTripleCol": "Triple",
    "detail.pricingChildCol": "Child (2–12)",
    "detail.flightDetailsTitle": "Flight details",
    "detail.flightDepartureLabel": "Departure",
    "detail.flightReturnLabel": "Return",
    "detail.program": "Program",
    "detail.included": "Included",
    "detail.notIncluded": "Not included",
    "detail.galleryOpen": "Open photo gallery",
    "detail.galleryPrev": "Previous photo",
    "detail.galleryNext": "Next photo",
    "detail.galleryThumbPin": "Preview or select gallery photo",
    "detail.galleryCarouselRegion": "Trip photos",

    // Archive / Search Page
    "archive.title": "All Trips",
    "archive.resultsFound": "trips found",
    "archive.searchPlaceholder": "Search by title...",
    "archive.priceRange": "Price Range",
    "archive.specialFilters": "Travel Preferences",
    "archive.featuredPicks": "Top Picks",
    "archive.sortBy": "Sort By",
    "archive.sort.recommended": "Recommended",
    "archive.sort.priceAsc": "Lowest Price",
    "archive.sort.priceDesc": "Highest Price",
    "archive.sort.durationAsc": "Shortest Duration",
    "archive.duration": "Duration",
    "archive.departureMonth": "Departure month",
    "archive.days": "Days",
    "archive.country": "Country",
    "archive.transport": "Transport",
    "archive.departureCity": "Departure City",
    "archive.category": "Category",
    "archive.tripType": "Trip Type",
    "archive.all": "All",
    "archive.group": "Group Trips",
    "archive.individual": "Individual",
    "archive.more": "MORE",
    "archive.noResults": "No trips match your filters.",

    "trips.disabledSeoTitle": "Valitsa Travel",
    "trips.disabledSeoDescription":
      "Contact us for travel planning and inquiries.",
    "trips.disabledHeading": "Trips unavailable",
    "trips.disabledBody":
      "Our trip listings are not shown at the moment. Use the contact button in the menu and we will assist you.",
    "trips.disabledHomeLink": "Back to home",

    // Trip Types
    "tripType.Exotic": "Exotic",
    "tripType.Road Trip": "Road Trip",
    "tripType.Flight": "Flight",

    // Not Found
    "notFound.message": "Oops! Page not found",
    "notFound.backHome": "Return to Home",

    // Advanced Search
    "search.title": "Advanced Search",
    "search.destination": "Destination",
    "search.internal": "Internal",
    "search.external": "External",
    "search.duration": "Duration (Days)",
    "search.category": "Category",
    "search.cultural": "Cultural",
    "search.adventure": "Adventure",
    "search.religious": "Religious",
    "search.wellness": "Wellness",
    "search.wildlife": "Wildlife",
    "search.expedition": "Expedition",
    "search.priceRange": "Price Range",
    "search.transport": "Transport Mode",
    "search.bus": "Bus",
    "search.plane": "Plane",
    "search.ship": "Ship",
    "search.apply": "Apply Filters",
    "search.reset": "Reset Filters",
    "search.filters": "Filters",

    // Countries
    "country.Greece": "Greece",
    "country.Italy": "Italy",
    "country.Japan": "Japan",
    "country.Iceland": "Iceland",
    "country.Switzerland": "Switzerland",
    "country.Tanzania": "Tanzania",
    "country.Chile": "Chile",
    "country.France": "France",
    "country.Peru": "Peru",
    "country.Egypt": "Egypt",
    "country.USA": "USA",

    // Footer
    "footer.rights": "© 2026 Valitsa Travel. All rights reserved.",
    "footer.devCreditPrefix": "Design & Development by: ",
    "footer.devName": "Athanasios Oikonomou",

    // Admin
    "admin.language": "Language",
    "admin.openMenu": "Open menu",
    "admin.signOut": "Sign out",
    "admin.dashboardTitle": "Dashboard",
    "admin.dashboardSubtitle": "Overview of your catalog and inquiries.",
    "admin.widgetTrips": "Trips",
    "admin.widgetTripsHint": "Open trip catalog",
    "admin.widgetInquiries": "Inquiries",
    "admin.widgetInquiriesHint": "Open inquiry inbox",
    "admin.tripsTitle": "Trips",
    "admin.tripsSubtitle": "Manage listings and analytics.",
    "admin.navigationTitle": "Navigation",
    "admin.navigationSubtitle": "Seasonal labels and navbar order.",
    "admin.navigationOrphansHeading": "Keys from trips without a config yet",
    "admin.navigationOrphansHint":
      "These seasonal keys are stored on trips but are not in the nav config yet. Add labels to show them in the navbar.",
    "admin.navigationOrphansEmpty":
      "No orphan seasonal keys. All trip values have a matching config.",
    "admin.navigationConfigsHeading": "Seasonal configs",
    "admin.navigationConfigsEmpty":
      "No seasonal configs yet. Use Add New Season above, or add labels for a trip key in the section below.",
    "admin.navigationAddSeasonButton": "Add New Season",
    "admin.navigationNewSeasonTitle": "New season",
    "admin.navigationNewSeasonDesc":
      "Create a seasonal key and labels for the navbar and trip editor.",
    "admin.navigationNewSeasonKey": "Unique key (slug)",
    "admin.navigationNewSeasonKeyPlaceholder": "summer-2026",
    "admin.navigationKeyInvalid":
      "Use lowercase letters, numbers, hyphens, or underscores only. No spaces.",
    "admin.navigationKey": "Key",
    "admin.navigationLabelEl": "Label (Greek)",
    "admin.navigationLabelEn": "Label (English)",
    "admin.navigationDisplayOrder": "Display order",
    "admin.navigationActive": "Active",
    "admin.navigationCreate": "Create config",
    "admin.navigationSave": "Save",
    "admin.navigationDelete": "Delete",
    "admin.navigationDeleteConfirmTitle": "Delete this seasonal config?",
    "admin.navigationDeleteConfirmBody":
      "This removes the config permanently. Trips that use this key ({n}) will have seasonal mode turned off and the seasonal name cleared.",
    "admin.navigationDeleted": "Seasonal config deleted",
    "admin.navigationDeletedTrips": "{n} trip(s) updated",
    "admin.navigationDeleteFailed": "Could not delete config",
    "admin.navigationCreated": "Config created",
    "admin.navigationUpdated": "Config updated",
    "admin.navigationSaveFailed": "Could not save config",
    "admin.navigationLoadErrorTitle": "Could not load navigation settings",
    "admin.navigationLoadErrorHint":
      "If this persists, check the API logs. For missing tables, run the SQL migration in Supabase (see hint below when applicable).",
    "admin.navigationLoadErrorHintTableMissing":
      "Your Supabase credentials are working. The seasonal tables are not created yet. In Supabase: SQL → New query → paste the file supabase/migrations/20260406120000_seasonal_navigation.sql from this repository → Run. Then refresh this page.",
    "admin.navigationLoadErrorHintEnv":
      "The API cannot use Supabase: set VITE_SUPABASE_URL or SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in the project root .env or server/.env, then restart the Node API (npm run dev or node server/index.js).",
    "admin.navigationLoadErrorApiUnreachableBody":
      "The server returned the public website HTML instead of the API. Requests to /api are not reaching Node—this is a hosting/routing issue, not a missing database table.",
    "admin.navigationLoadErrorHintApiUnreachable":
      "Fix: (1) Configure the host so /api is handled by your Node app (Passenger or nginx proxy to Express). (2) Or set VITE_API_BASE_URL in .env to the base URL where Express runs (open /api/health there—it must return JSON {\"ok\":true}), run npm run build, and upload the new dist.",
    "admin.navigationLoadErrorInvalidJsonBody":
      "The response was not valid JSON. Confirm the URL hits the Node API, not static hosting only.",
    "admin.tripIsSeasonal": "Seasonal trip",
    "admin.tripSeasonalName": "Season",
    "admin.tripSeasonalPlaceholder": "Choose a season",
    "admin.tripSeasonalRequired": "Select a season when seasonal mode is on.",
    "admin.tripAddSeasonNav": "Add new season",
    "admin.leadsTitle": "Inquiries",
    "admin.leadsSubtitle": "Inquiries and follow-ups.",
    "admin.catalog": "Catalog",
    "admin.name": "Name",
    "admin.clicks": "Clicks",
    "admin.forms": "Interested",
    "admin.featured": "Featured",
    "admin.untitled": "Untitled",
    "admin.tripTablePhoto": "Image",
    "admin.tripTableEdit": "Edit",
    "admin.tripTableDelete": "Delete",
    "admin.tripDeleteConfirmTitle": "Are you sure?",
    "admin.tripDeleteConfirmMessage":
      "This action cannot be undone. The trip will be permanently deleted.",
    "admin.tripDeleteCancel": "Cancel",
    "admin.tripDeleteConfirm": "Delete",
    "admin.tripDeleted": "The trip was deleted successfully.",
    "admin.tripDeleteFailed": "Could not delete trip.",
    "admin.editTrip": "Edit trip",
    "admin.addTrip": "Add trip",
    "admin.editTripDesc":
      "English and Greek fields; rich text is stored as HTML.",
    "admin.titleEn": "Title (English)",
    "admin.titleEl": "Title (Greek)",
    "admin.heroImage": "Hero image",
    "admin.mainPhotoFeatured": "Main Photo (Featured)",
    "admin.galleryPhotos": "Gallery Photos",
    "admin.galleryPhotosHint":
      "Up to four additional images, shown in order. Use the X on a thumbnail to remove it.",
    "admin.tripGalleryDropHint": "Drop or select 1–4 images",
    "admin.tripGalleryRemove": "Remove from gallery",
    "admin.tripGalleryRemoveShort": "Remove",
    "admin.tripGalleryDownload": "Download",
    "admin.tripGalleryPreviewOpen": "Open full preview",
    "admin.tripGalleryPreviewClose": "Close preview",
    "admin.tripGalleryPreviewTitle": "Gallery image",
    "admin.tripGalleryEmptySlot": "Empty",
    "admin.descriptionEn": "Description (English)",
    "admin.descriptionEl": "Description (Greek)",
    "admin.tripNotesEn": "Trip notes (English)",
    "admin.tripNotesEl": "Trip notes (Greek)",
    "admin.programEn": "Program (English)",
    "admin.programEl": "Program (Greek)",
    "admin.includedEn": "Included (English)",
    "admin.includedEl": "Included (Greek)",
    "admin.cancel": "Cancel",
    "admin.save": "Save",
    "admin.saving": "Saving…",
    "admin.tripSaved": "Trip saved",
    "admin.tripSaveFailed": "Could not save trip",
    "admin.tripValidationFailed": "Please fix the form errors",
    "admin.tripValidationToastPricingRow": "Pricing row {n}",
    "admin.tripValidationToastDepartureRow": "Departure row {n}",
    "admin.tripValidationToastFlight": "Flight details",
    "admin.tripValidationSavedSectionOtherErrors":
      "This section was saved. Other required fields on the main form still need attention before saving the trip.",
    "admin.tripPricingDepartureMismatch":
      "Each pricing row must use the same month as the departure row in the same position.",
    "admin.tripPricingDepartureDaysMismatch":
      "Each pricing row must use the same days as the departure row in the same position.",
    "admin.tripPricingDepartureRowMissing":
      "Each pricing row needs a matching departure row (same order). Add departures first or remove extra pricing rows.",
    "admin.tripPricingDepartureNoMatchingWindow":
      "Pick at least one day for this month, and only days you selected in Departure dates for that month.",
    "admin.tripDepartureModalTitle": "Departure dates",
    "admin.tripDepartureModalOpenButton": "Edit departure dates",
    "admin.tripDepartureModalSummary": "{count} departure window(s)",
    "admin.tripDepartureModalSave": "Save",
    "admin.tripDepartureModalCancel": "Cancel",
    "admin.tripDepartureUnsavedTitle": "Unsaved departure changes",
    "admin.tripDepartureUnsavedDescription":
      "You have unsaved changes to departure dates. Save them before closing, or leave without saving.",
    "admin.tripDepartureUnsavedSaveAndClose": "Save and close",
    "admin.tripDepartureUnsavedDiscard": "Leave without saving",
    "admin.tripDepartureUnsavedKeepEditing": "Keep editing",
    "admin.tripPricingModalTitle": "Pricing per departure (hotel & rooms)",
    "admin.tripPricingModalOpenButton": "Edit pricing per departure",
    "admin.tripPricingModalSummary": "{count} pricing row(s)",
    "admin.tripPricingModalSave": "Save",
    "admin.tripPricingModalCancel": "Cancel",
    "admin.tripPricingUnsavedTitle": "Unsaved pricing changes",
    "admin.tripPricingUnsavedDescription":
      "You have unsaved changes to departure pricing. Save them before closing, or leave without saving.",
    "admin.tripPricingUnsavedSaveAndClose": "Save and close",
    "admin.tripPricingUnsavedDiscard": "Leave without saving",
    "admin.tripPricingUnsavedKeepEditing": "Keep editing",
    "admin.tripFlightModalTitle": "Flight details",
    "admin.tripFlightModalOpenButton": "Edit flight details",
    "admin.tripFlightModalSummary": "{count} flight leg(s) · {state}",
    "admin.tripFlightModalSummaryOn": "On",
    "admin.tripFlightModalSummaryOff": "Off",
    "admin.tripFlightModalLegsHint":
      "Each block is one leg on the trip page. Add or remove blocks as you need.",
    "admin.tripFlightModalSave": "Save",
    "admin.tripFlightModalCancel": "Cancel",
    "admin.tripFlightUnsavedTitle": "Unsaved flight details",
    "admin.tripFlightUnsavedDescription":
      "You have unsaved changes to flight details. Save them before closing, or leave without saving.",
    "admin.tripFlightUnsavedSaveAndClose": "Save and close",
    "admin.tripFlightUnsavedDiscard": "Leave without saving",
    "admin.tripFlightUnsavedKeepEditing": "Keep editing",
    "admin.tabGreek": "Ελληνικά",
    "admin.tabEnglish": "English",
    "admin.tripSinglePhotoHint":
      "Only one main (featured) photo per trip. Remove it to upload a different one.",
    "admin.tripRemoveImage": "Remove image",
    "admin.tripFieldRequired": "This field is required.",
    "admin.tripRichFieldRequired": "This section cannot be empty.",
    "admin.tripCommonSettings": "Pricing and visibility",
    "admin.tripStatus": "Trip status",
    "admin.tripStatusActive": "Active",
    "admin.tripStatusInactive": "Inactive",
    "admin.tripEnableEnglish": "Enable English translation",
    "admin.tripEnableEnglishHint":
      "When off, English fields are ignored. When on, all English fields are required like Greek.",
    "admin.tripLocationEl": "Location (Greek)",
    "admin.tripCountryEl": "Country (Greek)",
    "admin.tripTypeEl": "Type (Greek)",
    "admin.tripCategoryEl": "Category (Greek)",
    "admin.tripTransportEl": "Transport (Greek)",
    "admin.tripDateRangeEl": "Date range (Greek)",
    "admin.tripDepartureCityEl": "Departure city (Greek)",
    "admin.tripLocationEn": "Location (English)",
    "admin.tripCountryEn": "Country (English)",
    "admin.tripTypeEn": "Type (English)",
    "admin.tripCategoryEn": "Category (English)",
    "admin.tripTransportEn": "Transport (English)",
    "admin.tripDateRangeEn": "Date range (English)",
    "admin.tripDepartureDates": "Departure dates",
    "admin.tripDepartureAddRow": "Add departure",
    "admin.tripDepartureRemoveRow": "Remove departure",
    "admin.tripDepartureMonth": "Month",
    "admin.tripDepartureDaysPick": "Days of departure",
    "admin.tripDepartureDayInvalid": "Pick only valid days for this month.",
    "admin.tripDepartureStart": "Start date",
    "admin.tripDepartureEnd": "End date",
    "admin.tripDepartureLabelEl": "Label (Greek, optional)",
    "admin.tripDepartureLabelEn": "Label (English, optional)",
    "admin.tripDepartureLabelsElSection": "Departure window labels (Greek)",
    "admin.tripLogisticsOnEnglishTabHint":
      "Dates, prices, and English labels are edited in the English tab.",
    "admin.tripDepartureLabelsElEmpty":
      "No departure windows yet. Add them in the English tab to enter Greek labels here.",
    "admin.tripDepartureRowGreek": "Departure {n} (Greek label)",
    "admin.tripPricingHotelElSection": "Hotel names (Greek)",
    "admin.tripPricingHotelElEmpty":
      "No pricing segments yet. Add segments in the English tab to enter Greek hotel names here.",
    "admin.tripPricingRowGreek": "Segment {n} (Greek hotel)",
    "admin.tripFlightDetailsElSection": "Flight details (Greek)",
    "admin.tripFlightDetailsElDisabled":
      "Turn on flight details in the English tab to enter Greek text here.",
    "admin.tripFlightDetailsElEmpty":
      "No flight legs yet. Add legs in the English tab to enter Greek text here.",
    "admin.tripDepartureLabelOptional": "Overrides automatic date text if set",
    "admin.tripDepartureRangeOrder": "End date must be on or after start date.",
    "admin.tripDepartureCityEn": "Departure city (English)",
    "admin.tripProgramDays": "Days",
    "admin.tripDaysPlaceholder": "e.g. 1, 1-2, 4-7",
    "admin.tripDaysInvalid": "Enter a day or range like 1, 1-2, or 4-7.",
    "admin.transportMenu": "Transport modes",
    "admin.transportPlaceholder": "Select transport modes",
    "admin.tripPriceNum": "Price",
    "admin.tripDurationDays": "Duration (days)",
    "admin.tripPricingSegmentsTitle": "Per-departure pricing (hotel and rooms)",
    "admin.tripPricingSegmentsHint":
      "Each row is a separate offer. Overlapping days across rows are allowed for display but avoid if they conflict.",
    "admin.tripPricingSegmentsEmpty": "No segments yet. Use Add segment or leave empty and use departure dates above.",
    "admin.tripPricingOnlyDeparturesHint":
      "Only months and days from Departure dates appear here; each pricing row can use a different subset.",
    "admin.tripPricingNeedDeparturesFirst":
      "Add at least one departure window with days selected (Departure dates above) before adding pricing segments.",
    "admin.tripPricingDeparturePatternLabel": "Departure dates",
    "admin.tripPricingSelectDepartureDays": "Select days…",
    "admin.tripPricingDaysMultiHint":
      "Tap to select days for this offer. Add another segment for the same month with a different combination (e.g. different hotel).",
    "admin.tripPricingSegmentAdd": "Add segment",
    "admin.tripPricingSegmentRemove": "Remove segment",
    "admin.tripPricingHotelEl": "Hotel (Greek)",
    "admin.tripPricingHotelEn": "Hotel (English)",
    "admin.tripPricingDouble": "Double room",
    "admin.tripPricingSingle": "Single room",
    "admin.tripPricingTriple": "Triple room (τρίκλινο)",
    "admin.tripPricingChild": "Child (2–12)",
    "admin.tripFlightDetailsSection": "Flight details",
    "admin.tripFlightDetailsHint":
      "Optional: add one or more departure/return pairs (Greek and English). Shown on the trip page when enabled.",
    "admin.tripFlightDetailsEnable": "Show flight details on trip page",
    "admin.tripFlightDetailsOn": "On",
    "admin.tripFlightDetailsOff": "Off",
    "admin.tripFlightLegAdd": "Add flight set",
    "admin.tripFlightLegLabel": "Set {n}",
    "admin.tripFlightLangEl": "Greek",
    "admin.tripFlightLangEn": "English",
    "admin.tripFlightLegRemove": "Remove flight set",
    "admin.tripFlightLegsEmpty": "No flight sets yet. Use Add flight set.",
    "admin.tripFlightDepartureEl": "Departure (Greek)",
    "admin.tripFlightReturnEl": "Return (Greek)",
    "admin.tripFlightDepartureEn": "Departure (English)",
    "admin.tripFlightReturnEn": "Return (English)",
    "admin.tripFeatured": "Featured trip",
    "admin.tripProgramTimeline": "Itinerary (by day)",
    "admin.tripAddDay": "Add day",
    "admin.tripRemoveDay": "Remove day",
    "admin.tripDayNumber": "Day #",
    "admin.tripDayTitle": "Day title",
    "admin.tripDayDescription": "Day description",
    "admin.tripIncludedEl": "What's included (Greek)",
    "admin.tripTagsEl": "Tags (Greek)",
    "admin.tripIncludedEn": "What's included (English)",
    "admin.tripNotIncludedEl": "Not included (Greek)",
    "admin.tripNotIncludedEn": "Not included (English)",
    "admin.tripTagsEn": "Tags (English)",
    "admin.tripArrayHint": "Type and press Enter",
    "admin.tripProgramMinDay": "Add at least one itinerary day.",
    "admin.tripProgramNeedsContent":
      "Add a title or description for at least one day.",
    "admin.tripIncludedMin": "Add at least one included item.",
    "admin.inbox": "Inbox",
    "admin.inquiry": "Inquiry",
    "admin.from": "From",
    "admin.trip": "Trip",
    "admin.message": "Message",
    "admin.status": "Status",
    "admin.internalNotes": "Internal notes",
    "admin.notesPlaceholder": "Private notes…",
    "admin.loginTitle": "Admin sign in",
    "admin.loginSubtitle": "Enter your credentials to access the dashboard.",
    "admin.email": "Email",
    "admin.password": "Password",
    "admin.signingIn": "Signing in…",
    "admin.signIn": "Sign in",
    "admin.unauthorizedToast": "Unauthorized: admin access required",
    "admin.sessionExpiredToast":
      "Your session has expired. Please sign in again.",
    "admin.forbiddenAccessToast":
      "Access denied. Admin privileges are required. You have been signed out.",
    "admin.signInFailed": "Sign in failed",
    "admin.close": "Close",
    "admin.activityFeed": "Activity",
    "admin.timelineCustomer": "Customer",
    "admin.timelineSystem": "System",
    "admin.timelineAdmin": "Admin",
    "admin.timelineYou": "You",
    "admin.commentPlaceholder": "Write an internal comment…",
    "admin.postComment": "Post comment",
    "admin.postingComment": "Posting…",
    "admin.commentPosted": "Comment added",
    "admin.commentFailed": "Could not post comment",
    "admin.statusSaved": "Status saved",
    "admin.saveStatus": "Save status",
    "admin.commentsLoadFailed": "Could not load comments",
    "admin.timelineOlderAbove": "Older messages above",
    "admin.timelineNewerBelow": "More messages below",
    "admin.editor.toolbar": "Formatting",
    "admin.editor.bold": "Bold",
    "admin.editor.italic": "Italic",
    "admin.editor.underline": "Underline",
    "admin.editor.bulletList": "Bullet list",
    "admin.editor.orderedList": "Numbered list",
    "admin.editor.link": "Link",
    "admin.editor.linkPrompt": "Paste or type a URL",
    "admin.editor.attachFile": "Attach file",
    "admin.editor.attachUploaded": "Attachment added",
    "admin.editor.attachFailed": "Upload failed. Please try again.",
    "admin.inquiryAttachmentDownload": "Download",
    "admin.inquiryAttachmentLinkLoading": "Preparing link…",
    "admin.inquiryAttachmentDownloadFailed":
      "Could not open the file. Please try again.",
    "admin.inquiryAttachmentPreviewTitle": "Preview",
    "admin.inquiryAttachmentPreviewTooltip": "Preview",
    "admin.inquiryAttachmentPreviewDownloadAria": "Download attachment",
    "admin.inquiryAttachmentPreviewCloseAria": "Close preview",
    "admin.inquiryAttachmentPreviewPrevAria": "Previous attachment",
    "admin.inquiryAttachmentPreviewNextAria": "Next attachment",
    "admin.inquiryAttachmentPreviewLoadFailed": "Could not load the preview.",
    "admin.inquiryAttachmentGalleryLabel": "Attached files",
    "admin.inquiryAttachmentPendingLabel": "Pending attachments",
    "admin.inquiryAttachmentRemove": "Remove",
    "admin.inquiryAttachmentUploading": "Uploading…",
    "admin.inquiryAttachmentErrMaxFiles":
      "You can attach up to 5 files per comment.",
    "admin.inquiryAttachmentErrFileTooLarge":
      "Each file must be at most 10 MB.",
    "admin.inquiryAttachmentErrTotalTooLarge":
      "Total size of attachments must be at most 50 MB.",
    "admin.inquiryAttachmentAddMore": "Add more files",
    "admin.inquiryAttachmentRemovePending": "Remove from queue",
    "admin.inquiryAttachmentDeleteSaved": "Delete attachment",
    "admin.inquiryAttachmentUploadProgress": "Upload progress",
    "admin.inquiryAttachmentUploadBatchFailed":
      "Upload failed. Please try again.",
    "admin.inquiryAttachmentDeleteFailed": "Could not delete the attachment.",
    "admin.inquiryQuickPhone": "Called by phone",
    "admin.inquiryQuickEmail": "Offer email sent",
    "admin.inquiryQuickFollowUp": "Follow-up scheduled",
    "admin.copyMessage": "Copy message",
    "admin.copied": "Copied",
    "admin.editor.fontSize": "Font size",
    "admin.editor.sizeDefault": "Default",
    "admin.editor.sizeSmall": "Small",
    "admin.editor.sizeNormal": "Normal",
    "admin.editor.sizeLarge": "Large",
    "admin.editor.sizeXl": "Extra large",
    "admin.statusNew": "New",
    "admin.statusContacted": "Contacted",
    "admin.statusResolved": "Resolved",
    "admin.statusSaveFailed": "Could not save status",
  },
  gr: {
    // Navbar
    "nav.brand": "VALITSA",
    "nav.terms": "Όροι & Προϋποθέσεις",
    "nav.daily": "Ημερήσιες Εκδρομές",
    "nav.twoday": "2ήμερες Εκδρομές",
    "nav.multiday": "Πολυήμερες Εκδρομές",
    "nav.multidayAll": "Όλες οι πολυήμερες εκδρομές",
    "nav.multidayDaysOption": "Εκδρομές {n} ημερών",
    "nav.multidayAria": "Μενού πολυήμερων εκδρομών",
    "nav.internal": "Εκδρομές Εσωτερικού",
    "nav.external": "Εκδρομές Εξωτερικού",
    "nav.contactBtn": "Επικοινωνία",
    "nav.toggleLanguage": "Αλλαγή γλώσσας",
    "nav.toggleTheme": "Αλλαγή θέματος",
    "nav.menu": "Μενού",
    "nav.seasonal": "Εποχιακές",
    "nav.seasonalAria": "Μενού εποχιακών εκδρομών",
    "nav.more": "Περισσότερα",
    "nav.moreAria": "Περισσότερες κατηγορίες ταξιδιών",
    "archive.seasonal": "Εποχιακές",
    "archive.seasonalAll": "Όλα τα ταξίδια",

    // Common
    "common.close": "Κλείσιμο",
    "common.scrollUp": "Επιστροφή στην κορυφή",
    "common.scrollUpAria": "Κύλιση στην κορυφή",

    // Contact Modal
    "contact.title": "Επικοινωνία",
    "contact.callUs": "Καλέστε μας",
    "contact.whatsapp": "WhatsApp",
    "contact.whatsappDesc": "Συνομιλήστε μαζί μας άμεσα",
    "contact.viber": "Viber",
    "contact.viberDesc": "Στείλτε μας μήνυμα στο Viber",
    "contact.sendMessage": "Στείλτε μήνυμα",
    "contact.sendMessageDesc":
      "Συμπληρώστε τη φόρμα και θα επικοινωνήσουμε μαζί σας",
    "contact.back": "Πίσω",
    "contact.send": "Αποστολή",
    "contact.sending": "Αποστολή...",
    "contact.sendFailed": "Αποτυχία αποστολής. Προσπαθήστε ξανά.",
    "contact.sent": "Το μήνυμα στάλθηκε!",
    "contact.sentDesc": "Θα επικοινωνήσουμε μαζί σας εντός 24 ωρών.",

    "validation.required": "Το πεδίο είναι υποχρεωτικό",
    "validation.emailInvalid": "Εισάγετε έγκυρη διεύθυνση email",
    "validation.phoneInvalid": "Εισάγετε έγκυρο αριθμό τηλεφώνου",

    // Hero
    "hero.label": "Λιγότερο ρουτίνα, περισσότερη ζωή",
    "hero.title": "Ετοιμάστε Βαλίτσες",
    "hero.subtitle":
      "Κάθε ταξίδι έχει μυστικούς προορισμούς που ο ταξιδιώτης δε γνωρίζει. -Martin Buber",
    "hero.cta": "Δείτε όλα τα ταξίδια μας",
    "hero.alt": "Εναέρια θέα σε ήρεμη τροπική ακτογραμμή",

    // Featured
    "featured.label": "Επιλεγμένες Συλλογές",
    "featured.title": "Κορυφαίες Αποδράσεις",
    "featured.viewAll": "Δείτε όλα τα ταξίδια",

    // Trip Grid
    "grid.label": "Επιλεγμένες Συλλογές",
    "grid.title": "Κορυφαίες Αποδράσεις",
    "grid.all": "Όλα",
    "grid.viewDetails": "Λεπτομέρειες",

    // Trip Card Quick Links
    "card.moreDuration": "Περισσότερα {duration} Ταξίδια",
    "card.moreType": "Περισσότερα {type} Ταξίδια",
    "card.trip": "Ταξίδι",
    "card.seasonalFallback": "Εποχιακό",

    // Trip Detail
    "detail.startingFrom": "Από",
    "detail.expressInterest": "Εκδηλώστε Ενδιαφέρον",
    "detail.firstName": "Όνομα",
    "detail.lastName": "Επώνυμο",
    "detail.email": "Email",
    "detail.mobile": "Κινητό",
    "detail.message": "Πείτε μας τις προτιμήσεις σας...",
    "detail.sendInquiry": "Αποστολή",
    "detail.sending": "Αποστολή...",
    "detail.sendFailed": "Αποτυχία αποστολής αιτήματος. Προσπαθήστε ξανά.",
    "detail.inquirySent": "Το αίτημα στάλθηκε",
    "detail.inquiryMsg": "Θα επικοινωνήσουμε εντός 24 ωρών.",
    "detail.description": "Περιγραφή",
    "detail.tripNotes": "Σημειώσεις",
    "detail.departureDates": "Ημερομηνίες αναχωρήσεων",
    "detail.departureDatesMonthCol": "Μήνας",
    "detail.departureDatesDaysCol": "Ημέρες",
    "detail.pricingSegmentsTitle": "Αναχωρήσεις και τιμές",
    "detail.pricingDepartures": "Αναχωρήσεις",
    "detail.pricingDepartureCity": "Πόλη αναχώρησης",
    "detail.pricingHotelCol": "Ξενοδοχείο",
    "detail.pricingDurationCol": "Διάρκεια",
    "detail.pricingDoubleCol": "Δίκλινο",
    "detail.pricingSingleCol": "Μονόκλινο",
    "detail.pricingTripleCol": "Τρίκλινο",
    "detail.pricingChildCol": "Παιδικό (2–12)",
    "detail.flightDetailsTitle": "Πληροφορίες πτήσεων",
    "detail.flightDepartureLabel": "Αναχώρηση",
    "detail.flightReturnLabel": "Επιστροφή",
    "detail.program": "Πρόγραμμα",
    "detail.included": "Περιλαμβάνονται",
    "detail.notIncluded": "Δεν περιλαμβάνονται",
    "detail.galleryOpen": "Άνοιγμα συλλογής φωτογραφιών",
    "detail.galleryPrev": "Προηγούμενη φωτογραφία",
    "detail.galleryNext": "Επόμενη φωτογραφία",
    "detail.galleryThumbPin": "Προεπισκόπηση ή επιλογή φωτογραφίας συλλογής",
    "detail.galleryCarouselRegion": "Φωτογραφίες ταξιδιού",

    // Archive / Search Page
    "archive.title": "Όλα τα Ταξίδια",
    "archive.resultsFound": "ταξίδια βρέθηκαν",
    "archive.searchPlaceholder": "Αναζήτηση με τίτλο...",
    "archive.priceRange": "Εύρος Τιμής",
    "archive.specialFilters": "Προτιμήσεις Ταξιδιού",
    "archive.featuredPicks": "Κορυφαίες Επιλογές",
    "archive.sortBy": "Ταξινόμηση",
    "archive.sort.recommended": "Προτεινόμενα",
    "archive.sort.priceAsc": "Χαμηλότερη Τιμή",
    "archive.sort.priceDesc": "Υψηλότερη Τιμή",
    "archive.sort.durationAsc": "Μικρότερη Διάρκεια",
    "archive.duration": "Διάρκεια",
    "archive.departureMonth": "Μήνας αναχώρησης",
    "archive.days": "Ημέρες",
    "archive.country": "Χώρα",
    "archive.transport": "Μεταφορά",
    "archive.departureCity": "Πόλη Αναχώρησης",
    "archive.category": "Κατηγορία",
    "archive.tripType": "Τύπος Ταξιδιού",
    "archive.all": "Όλα",
    "archive.group": "Ομαδικά Ταξίδια",
    "archive.individual": "Ατομικά",
    "archive.more": "ΠΕΡΙΣΣΟΤΕΡΑ",
    "archive.noResults": "Δεν βρέθηκαν ταξίδια με αυτά τα φίλτρα.",

    "trips.disabledSeoTitle": "Valitsa Travel",
    "trips.disabledSeoDescription":
      "Επικοινωνήστε μαζί μας για οργάνωση ταξιδιών και ερωτήσεις.",
    "trips.disabledHeading": "Τα ταξίδια δεν είναι διαθέσιμα",
    "trips.disabledBody":
      "Η λίστα ταξιδιών δεν εμφανίζεται αυτή τη στιγμή. Χρησιμοποιήστε το κουμπί επικοινωνίας στο μενού και θα σας βοηθήσουμε.",
    "trips.disabledHomeLink": "Επιστροφή στην αρχική",

    // Trip Types
    "tripType.Exotic": "Εξωτικό",
    "tripType.Road Trip": "Οδικό",
    "tripType.Flight": "Αεροπορικό",

    // Not Found
    "notFound.message": "Ουπς! Η σελίδα δεν βρέθηκε",
    "notFound.backHome": "Επιστροφή στην Αρχική",

    // Advanced Search
    "search.title": "Σύνθετη Αναζήτηση",
    "search.destination": "Προορισμός",
    "search.internal": "Εσωτερικό",
    "search.external": "Εξωτερικό",
    "search.duration": "Διάρκεια (Ημέρες)",
    "search.category": "Κατηγορία",
    "search.cultural": "Πολιτιστικό",
    "search.adventure": "Περιπέτεια",
    "search.religious": "Θρησκευτικό",
    "search.wellness": "Ευεξία",
    "search.wildlife": "Άγρια Ζωή",
    "search.expedition": "Εξερεύνηση",
    "search.priceRange": "Εύρος Τιμής",
    "search.transport": "Μέσο Μεταφοράς",
    "search.bus": "Λεωφορείο",
    "search.plane": "Αεροπλάνο",
    "search.ship": "Πλοίο",
    "search.apply": "Εφαρμογή",
    "search.reset": "Επαναφορά Φίλτρων",
    "search.filters": "Φίλτρα",

    // Countries
    "country.Greece": "Ελλάδα",
    "country.Italy": "Ιταλία",
    "country.Japan": "Ιαπωνία",
    "country.Iceland": "Ισλανδία",
    "country.Switzerland": "Ελβετία",
    "country.Tanzania": "Τανζανία",
    "country.Chile": "Χιλή",
    "country.France": "Γαλλία",
    "country.Peru": "Περού",
    "country.Egypt": "Αίγυπτος",
    "country.USA": "ΗΠΑ",

    // Footer
    "footer.rights": "© 2026 Valitsa Travel. Με επιφύλαξη παντός δικαιώματος.",
    "footer.devCreditPrefix": "Σχεδιασμός & Υλοποίηση: ",
    "footer.devName": "Athanasios Oikonomou",

    // Admin
    "admin.language": "Γλώσσα",
    "admin.openMenu": "Άνοιγμα μενού",
    "admin.signOut": "Αποσύνδεση",
    "admin.dashboardTitle": "Πίνακας ελέγχου",
    "admin.dashboardSubtitle": "Επισκόπηση καταλόγου και αιτημάτων.",
    "admin.widgetTrips": "Ταξίδια",
    "admin.widgetTripsHint": "Άνοιγμα καταλόγου ταξιδιών",
    "admin.widgetInquiries": "Αιτήματα",
    "admin.widgetInquiriesHint": "Άνοιγμα εισερχομένων",
    "admin.tripsTitle": "Ταξίδια",
    "admin.tripsSubtitle": "Διαχείριση καταχωρίσεων και αναλυτικών.",
    "admin.navigationTitle": "Πλοήγηση",
    "admin.navigationSubtitle": "Ετικέτες εποχών και σειρά στη μπάρα.",
    "admin.navigationOrphansHeading": "Κλειδιά από ταξίδια χωρίς ρύθμιση ακόμα",
    "admin.navigationOrphansHint":
      "Αυτά τα κλειδιά υπάρχουν σε ταξίδια αλλά όχι στη ρύθμιση πλοήγησης. Προσθέστε ετικέτες για εμφάνιση στη μπάρα.",
    "admin.navigationOrphansEmpty": "Δεν υπάρχουν ορφανά εποχιακά κλειδιά.",
    "admin.navigationConfigsHeading": "Ρυθμίσεις εποχών",
    "admin.navigationConfigsEmpty":
      "Δεν υπάρχουν ρυθμίσεις. Χρησιμοποιήστε «Προσθήκη Νέας Εποχής» παραπάνω ή προσθέστε ετικέτες για κλειδί ταξιδιού στην ενότητα παρακάτω.",
    "admin.navigationAddSeasonButton": "Προσθήκη Νέας Εποχής",
    "admin.navigationNewSeasonTitle": "Νέα εποχή",
    "admin.navigationNewSeasonDesc":
      "Δημιουργία κλειδιού εποχής και ετικετών για τη μπάρα και το επεξεργαστή ταξιδιών.",
    "admin.navigationNewSeasonKey": "Μοναδικό κλειδί (slug)",
    "admin.navigationNewSeasonKeyPlaceholder": "summer-2026",
    "admin.navigationKeyInvalid":
      "Χρησιμοποιήστε μόνο πεζά γράμματα, αριθμούς, παύλες ή κάτω παύλες. Χωρίς κενά.",
    "admin.navigationKey": "Κλειδί",
    "admin.navigationLabelEl": "Ετικέτα (ελληνικά)",
    "admin.navigationLabelEn": "Ετικέτα (αγγλικά)",
    "admin.navigationDisplayOrder": "Σειρά εμφάνισης",
    "admin.navigationActive": "Ενεργό",
    "admin.navigationCreate": "Δημιουργία",
    "admin.navigationSave": "Αποθήκευση",
    "admin.navigationDelete": "Διαγραφή",
    "admin.navigationDeleteConfirmTitle": "Διαγραφή αυτής της ρύθμισης εποχής;",
    "admin.navigationDeleteConfirmBody":
      "Η ρύθμιση θα διαγραφεί οριστικά. Τα ταξίδια που χρησιμοποιούν αυτό το κλειδί ({n}) θα αποσυνδεθούν: θα απενεργοποιηθεί ο εποχιακός τρόπος και θα καθαριστεί το όνομα εποχής.",
    "admin.navigationDeleted": "Η ρύθμιση εποχής διαγράφηκε",
    "admin.navigationDeletedTrips": "Ενημερώθηκαν {n} ταξίδι(α)",
    "admin.navigationDeleteFailed": "Αποτυχία διαγραφής",
    "admin.navigationCreated": "Η ρύθμιση δημιουργήθηκε",
    "admin.navigationUpdated": "Η ρύθμιση ενημερώθηκε",
    "admin.navigationSaveFailed": "Αποτυχία αποθήκευσης",
    "admin.navigationLoadErrorTitle": "Αποτυχία φόρτωσης ρυθμίσεων πλοήγησης",
    "admin.navigationLoadErrorHint":
      "Αν συνεχίζει, ελέγξτε τα logs του API. Για ελλιπείς πίνακες, εκτελέστε το SQL migration στο Supabase.",
    "admin.navigationLoadErrorHintTableMissing":
      "Τα διαπιστευτήρια Supabase λειτουργούν. Οι εποχιακοί πίνακες δεν έχουν δημιουργηθεί ακόμα. Στο Supabase: SQL → Νέο ερώτημα → επικολλήστε το αρχείο supabase/migrations/20260406120000_seasonal_navigation.sql από αυτό το repo → Εκτέλεση. Μετά ανανεώστε τη σελίδα.",
    "admin.navigationLoadErrorHintEnv":
      "Το API δεν μπορεί να χρησιμοποιήσει το Supabase: ορίστε VITE_SUPABASE_URL ή SUPABASE_URL και SUPABASE_SERVICE_ROLE_KEY στο .env στη ρίζα ή στο server/.env και επανεκκινήστε το Node API.",
    "admin.navigationLoadErrorApiUnreachableBody":
      "Ο διακομιστής επέστρεψε HTML της δημόσιας ιστοσελίδας αντί για το API. Τα αιτήματα στο /api δεν φτάνουν στο Node—πρόκειται για ρύθμιση hosting/δρομολόγησης, όχι για ελλιπή πίνακα στη βάση.",
    "admin.navigationLoadErrorHintApiUnreachable":
      "Λύση: (1) Ρυθμίστε τον host ώστε το /api να εξυπηρετείται από την εφαρμογή Node (Passenger ή nginx proxy προς Express). (2) Ή ορίστε VITE_API_BASE_URL στο .env στη βάση URL όπου τρέχει το Express (ανοίξτε εκεί /api/health—πρέπει να επιστρέφει JSON {\"ok\":true}), τρέξτε npm run build και ανεβάστε το νέο dist.",
    "admin.navigationLoadErrorInvalidJsonBody":
      "Η απάντηση δεν ήταν έγκυρο JSON. Βεβαιωθείτε ότι το URL οδηγεί στο Node API, όχι μόνο σε στατικά αρχεία.",
    "admin.tripIsSeasonal": "Εποχιακό ταξίδι",
    "admin.tripSeasonalName": "Εποχή",
    "admin.tripSeasonalPlaceholder": "Επιλέξτε εποχή",
    "admin.tripSeasonalRequired":
      "Επιλέξτε εποχή όταν είναι ενεργή η εποχιακή λειτουργία.",
    "admin.tripAddSeasonNav": "Νέα εποχή",
    "admin.leadsTitle": "Αιτήματα",
    "admin.leadsSubtitle": "Αιτήματα και παρακολούθηση.",
    "admin.catalog": "Κατάλογος",
    "admin.name": "Όνομα",
    "admin.clicks": "Κλικ",
    "admin.forms": "Ενδιαφερόμενοι",
    "admin.featured": "Προτεινόμενο",
    "admin.untitled": "Χωρίς τίτλο",
    "admin.tripTablePhoto": "Φωτογραφία",
    "admin.tripTableEdit": "Επεξεργασία",
    "admin.tripTableDelete": "Διαγραφή",
    "admin.tripDeleteConfirmTitle": "Είστε σίγουροι;",
    "admin.tripDeleteConfirmMessage":
      "Αυτή η ενέργεια δεν μπορεί να αναιρεθεί. Το ταξίδι θα διαγραφεί οριστικά.",
    "admin.tripDeleteCancel": "Ακύρωση",
    "admin.tripDeleteConfirm": "Διαγραφή",
    "admin.tripDeleted": "Το ταξίδι διαγράφηκε με επιτυχία.",
    "admin.tripDeleteFailed": "Αποτυχία διαγραφής ταξιδιού.",
    "admin.editTrip": "Επεξεργασία ταξιδιού",
    "admin.addTrip": "Προσθήκη Ταξιδιού",
    "admin.editTripDesc":
      "Πεδία στα αγγλικά και ελληνικά· το πλούσιο κείμενο αποθηκεύεται ως HTML.",
    "admin.titleEn": "Τίτλος (αγγλικά)",
    "admin.titleEl": "Τίτλος (ελληνικά)",
    "admin.heroImage": "Κύρια εικόνα",
    "admin.mainPhotoFeatured": "Κύρια φωτογραφία (προβεβλημένη)",
    "admin.galleryPhotos": "Φωτογραφίες συλλογής",
    "admin.galleryPhotosHint":
      "Έως τέσσερις επιπλέον εικόνες, με τη σειρά. Χρησιμοποιήστε το X για αφαίρεση.",
    "admin.tripGalleryDropHint": "Αποθέστε ή επιλέξτε έως 4 εικόνες",
    "admin.tripGalleryRemove": "Αφαίρεση από τη συλλογή",
    "admin.tripGalleryRemoveShort": "Αφαίρεση",
    "admin.tripGalleryDownload": "Λήψη",
    "admin.tripGalleryPreviewOpen": "Πλήρης προεπισκόπηση",
    "admin.tripGalleryPreviewClose": "Κλείσιμο προεπισκόπησης",
    "admin.tripGalleryPreviewTitle": "Εικόνα συλλογής",
    "admin.tripGalleryEmptySlot": "Κενό",
    "admin.descriptionEn": "Περιγραφή (αγγλικά)",
    "admin.descriptionEl": "Περιγραφή (ελληνικά)",
    "admin.tripNotesEn": "Σημειώσεις ταξιδιού (αγγλικά)",
    "admin.tripNotesEl": "Σημειώσεις ταξιδιού (ελληνικά)",
    "admin.programEn": "Πρόγραμμα (αγγλικά)",
    "admin.programEl": "Πρόγραμμα (ελληνικά)",
    "admin.includedEn": "Περιλαμβάνονται (αγγλικά)",
    "admin.includedEl": "Περιλαμβάνονται (ελληνικά)",
    "admin.cancel": "Ακύρωση",
    "admin.save": "Αποθήκευση",
    "admin.saving": "Αποθήκευση…",
    "admin.tripSaved": "Το ταξίδι αποθηκεύτηκε",
    "admin.tripSaveFailed": "Αποτυχία αποθήκευσης ταξιδιού",
    "admin.tripValidationFailed": "Διορθώστε τα σφάλματα στη φόρμα",
    "admin.tripValidationToastPricingRow": "Γραμμή τιμών {n}",
    "admin.tripValidationToastDepartureRow": "Γραμμή αναχώρησης {n}",
    "admin.tripValidationToastFlight": "Λεπτομέρειες πτήσης",
    "admin.tripValidationSavedSectionOtherErrors":
      "Αυτή η ενότητα αποθηκεύτηκε. Άλλα υποχρεωτικά πεδία στη φόρμα χρειάζονται ακόμη διόρθωση πριν την αποθήκευση του ταξιδιού.",
    "admin.tripPricingDepartureMismatch":
      "Κάθε γραμμή τιμολόγησης πρέπει να έχει τον ίδιο μήνα με την αντίστοιχη γραμμή αναχώρησης.",
    "admin.tripPricingDepartureDaysMismatch":
      "Κάθε γραμμή τιμολόγησης πρέπει να έχει τις ίδιες ημέρες με την αντίστοιχη γραμμή αναχώρησης.",
    "admin.tripPricingDepartureRowMissing":
      "Κάθε γραμμή τιμολόγησης χρειάζεται αντίστοιχη γραμμή αναχώρησης (ίδια σειρά). Προσθέστε αναχωρήσεις πρώτα ή αφαιρέστε επιπλέον γραμμές τιμολόγησης.",
    "admin.tripPricingDepartureNoMatchingWindow":
      "Επιλέξτε τουλάχιστον μία ημέρα για τον μήνα και μόνο ημέρες που έχετε ορίσει στις ημερομηνίες αναχώρησης για αυτόν τον μήνα.",
    "admin.tripDepartureModalTitle": "Ημερομηνίες αναχώρησης",
    "admin.tripDepartureModalOpenButton": "Επεξεργασία ημερομηνιών αναχώρησης",
    "admin.tripDepartureModalSummary": "{count} παράθυρο(α) αναχώρησης",
    "admin.tripDepartureModalSave": "Αποθήκευση",
    "admin.tripDepartureModalCancel": "Ακύρωση",
    "admin.tripDepartureUnsavedTitle": "Μη αποθηκευμένες αλλαγές αναχωρήσεων",
    "admin.tripDepartureUnsavedDescription":
      "Έχετε μη αποθηκευμένες αλλαγές στις ημερομηνίες αναχώρησης. Αποθηκεύστε πριν το κλείσιμο ή εγκαταλείψτε χωρίς αποθήκευση.",
    "admin.tripDepartureUnsavedSaveAndClose": "Αποθήκευση και κλείσιμο",
    "admin.tripDepartureUnsavedDiscard": "Έξοδος χωρίς αποθήκευση",
    "admin.tripDepartureUnsavedKeepEditing": "Συνέχεια επεξεργασίας",
    "admin.tripPricingModalTitle": "Τιμές ανά αναχώρηση (ξενοδοχείο και δωμάτια)",
    "admin.tripPricingModalOpenButton": "Επεξεργασία τιμών ανά αναχώρηση",
    "admin.tripPricingModalSummary": "{count} γραμμή/ές τιμολόγησης",
    "admin.tripPricingModalSave": "Αποθήκευση",
    "admin.tripPricingModalCancel": "Ακύρωση",
    "admin.tripPricingUnsavedTitle": "Μη αποθηκευμένες αλλαγές τιμών",
    "admin.tripPricingUnsavedDescription":
      "Έχετε μη αποθηκευμένες αλλαγές στις τιμές ανά αναχώρηση. Αποθηκεύστε πριν το κλείσιμο ή εγκαταλείψτε χωρίς αποθήκευση.",
    "admin.tripPricingUnsavedSaveAndClose": "Αποθήκευση και κλείσιμο",
    "admin.tripPricingUnsavedDiscard": "Έξοδος χωρίς αποθήκευση",
    "admin.tripPricingUnsavedKeepEditing": "Συνέχεια επεξεργασίας",
    "admin.tripFlightModalTitle": "Λεπτομέρειες πτήσεων",
    "admin.tripFlightModalOpenButton": "Επεξεργασία λεπτομερειών πτήσεων",
    "admin.tripFlightModalSummary": "{count} σκέλος/η πτήσης · {state}",
    "admin.tripFlightModalSummaryOn": "Ενεργό",
    "admin.tripFlightModalSummaryOff": "Ανενεργό",
    "admin.tripFlightModalLegsHint":
      "Κάθε μπλοκ είναι ένα σκέλος στη σελίδα του ταξιδιού. Προσθέστε ή αφαιρέστε μπλοκ όπως χρειάζεται.",
    "admin.tripFlightModalSave": "Αποθήκευση",
    "admin.tripFlightModalCancel": "Ακύρωση",
    "admin.tripFlightUnsavedTitle": "Μη αποθηκευμένες λεπτομέρειες πτήσεων",
    "admin.tripFlightUnsavedDescription":
      "Έχετε μη αποθηκευμένες αλλαγές στις λεπτομέρειες πτήσεων. Αποθηκεύστε πριν το κλείσιμο ή εγκαταλείψτε χωρίς αποθήκευση.",
    "admin.tripFlightUnsavedSaveAndClose": "Αποθήκευση και κλείσιμο",
    "admin.tripFlightUnsavedDiscard": "Έξοδος χωρίς αποθήκευση",
    "admin.tripFlightUnsavedKeepEditing": "Συνέχεια επεξεργασίας",
    "admin.tabGreek": "Ελληνικά",
    "admin.tabEnglish": "English",
    "admin.tripSinglePhotoHint":
      "Μόνο μία κύρια (προβεβλημένη) φωτογραφία ανά ταξίδι. Αφαιρέστε την για να ανεβάσετε άλλη.",
    "admin.tripRemoveImage": "Αφαίρεση εικόνας",
    "admin.tripFieldRequired": "Υποχρεωτικό πεδίο.",
    "admin.tripRichFieldRequired": "Αυτή η ενότητα δεν μπορεί να είναι κενή.",
    "admin.tripCommonSettings": "Τιμολόγηση και εμφάνιση",
    "admin.tripStatus": "Κατάσταση ταξιδιού",
    "admin.tripStatusActive": "Ενεργό",
    "admin.tripStatusInactive": "Ανενεργό",
    "admin.tripEnableEnglish": "Ενεργοποίηση αγγλικής μετάφρασης",
    "admin.tripEnableEnglishHint":
      "Όταν είναι ανενεργό, τα αγγλικά πεδία αγνοούνται. Όταν είναι ενεργό, όλα τα αγγλικά πεδία είναι υποχρεωτικά όπως τα ελληνικά.",
    "admin.tripLocationEl": "Τοποθεσία (ελληνικά)",
    "admin.tripCountryEl": "Χώρα (ελληνικά)",
    "admin.tripTypeEl": "Τύπος (ελληνικά)",
    "admin.tripCategoryEl": "Κατηγορία (ελληνικά)",
    "admin.tripTransportEl": "Μεταφορά (ελληνικά)",
    "admin.tripDateRangeEl": "Χρονικό διάστημα (ελληνικά)",
    "admin.tripDepartureCityEl": "Πόλη αναχώρησης (ελληνικά)",
    "admin.tripLocationEn": "Τοποθεσία (αγγλικά)",
    "admin.tripCountryEn": "Χώρα (αγγλικά)",
    "admin.tripTypeEn": "Τύπος (αγγλικά)",
    "admin.tripCategoryEn": "Κατηγορία (αγγλικά)",
    "admin.tripTransportEn": "Μεταφορά (αγγλικά)",
    "admin.tripDateRangeEn": "Χρονικό διάστημα (αγγλικά)",
    "admin.tripDepartureDates": "Ημερομηνίες αναχωρήσεων",
    "admin.tripDepartureAddRow": "Προσθήκη αναχώρησης",
    "admin.tripDepartureRemoveRow": "Αφαίρεση αναχώρησης",
    "admin.tripDepartureMonth": "Μήνας",
    "admin.tripDepartureDaysPick": "Ημέρες αναχώρησης",
    "admin.tripDepartureDayInvalid": "Επιλέξτε έγκυρες ημέρες για αυτόν τον μήνα.",
    "admin.tripDepartureStart": "Ημερομηνία έναρξης",
    "admin.tripDepartureEnd": "Ημερομηνία λήξης",
    "admin.tripDepartureLabelEl": "Ετικέτα (ελληνικά, προαιρετικό)",
    "admin.tripDepartureLabelEn": "Ετικέτα (αγγλικά, προαιρετικό)",
    "admin.tripDepartureLabelsElSection": "Ετικέτες παραθύρων αναχώρησης (ελληνικά)",
    "admin.tripLogisticsOnEnglishTabHint":
      "Ημερομηνίες, τιμές και αγγλικές ετικέτες επεξεργάζονται στην καρτέλα «Αγγλικά».",
    "admin.tripDepartureLabelsElEmpty":
      "Δεν υπάρχουν ακόμα παράθυρα αναχώρησης. Προσθέστε τα στην καρτέλα «Αγγλικά» για να εισάγετε ελληνικές ετικέτες εδώ.",
    "admin.tripDepartureRowGreek": "Αναχώρηση {n} (ελληνική ετικέτα)",
    "admin.tripPricingHotelElSection": "Ονόματα ξενοδοχείων (ελληνικά)",
    "admin.tripPricingHotelElEmpty":
      "Δεν υπάρχουν ακόμα τμήματα τιμολόγησης. Προσθέστε τμήματα στην καρτέλα «Αγγλικά» για να εισάγετε ελληνικά ονόματα ξενοδοχείων εδώ.",
    "admin.tripPricingRowGreek": "Τμήμα {n} (ελληνικό ξενοδοχείο)",
    "admin.tripFlightDetailsElSection": "Λεπτομέρειες πτήσης (ελληνικά)",
    "admin.tripFlightDetailsElDisabled":
      "Ενεργοποιήστε τις λεπτομέρειες πτήσης στην καρτέλα «Αγγλικά» για να εισάγετε ελληνικό κείμενο εδώ.",
    "admin.tripFlightDetailsElEmpty":
      "Δεν υπάρχουν ακόμα σκέλη πτήσης. Προσθέστε σκέλη στην καρτέλα «Αγγλικά» για να εισάγετε ελληνικό κείμενο εδώ.",
    "admin.tripDepartureLabelOptional": "Αντικαθιστά το αυτόματο κείμενο ημερομηνιών αν συμπληρωθεί",
    "admin.tripDepartureRangeOrder": "Η ημερομηνία λήξης πρέπει να είναι ίδια ή μετά την έναρξη.",
    "admin.tripDepartureCityEn": "Πόλη αναχώρησης (αγγλικά)",
    "admin.tripProgramDays": "Ημέρες",
    "admin.tripDaysPlaceholder": "π.χ. 1, 1-2, 4-7",
    "admin.tripDaysInvalid": "Χρησιμοποιήστε ημέρα ή εύρος όπως 1, 1-2 ή 4-7.",
    "admin.transportMenu": "Μέσα μεταφοράς",
    "admin.transportPlaceholder": "Επιλέξτε μέσα μεταφοράς",
    "admin.tripPriceNum": "Τιμή",
    "admin.tripDurationDays": "Διάρκεια (ημέρες)",
    "admin.tripPricingSegmentsTitle": "Τιμές ανά αναχώρηση (ξενοδοχείο και δωμάτια)",
    "admin.tripPricingSegmentsHint":
      "Κάθε γραμμή είναι ξεχωριστή προσφορά. Επικαλυπτόμενες ημέρες επιτρέπονται για εμφάνιση, αλλά αποφύγετε αν συγκρούονται.",
    "admin.tripPricingSegmentsEmpty": "Δεν υπάρχουν τμήματα ακόμα. Προσθέστε τμήμα ή αφήστε κενό και χρησιμοποιήστε τις ημερομηνίες αναχώρησης πάνω.",
    "admin.tripPricingOnlyDeparturesHint":
      "Εμφανίζονται μόνο μήνες και ημέρες από τις ημερομηνίες αναχώρησης· κάθε γραμμή τιμών μπορεί να χρησιμοποιεί διαφορετικό υποσύνολο.",
    "admin.tripPricingNeedDeparturesFirst":
      "Προσθέστε τουλάχιστον ένα παράθυρο αναχώρησης με επιλεγμένες ημέρες (Ημερομηνίες αναχώρησης παραπάνω) πριν προσθέσετε γραμμές τιμολόγησης.",
    "admin.tripPricingDeparturePatternLabel": "Ημερομηνίες αναχώρησης",
    "admin.tripPricingSelectDepartureDays": "Επιλέξτε ημέρες…",
    "admin.tripPricingDaysMultiHint":
      "Πατήστε για να επιλέξετε ημέρες για αυτή την προσφορά. Προσθέστε νέα γραμμή για τον ίδιο μήνα με άλλο συνδυασμό (π.χ. άλλο ξενοδοχείο).",
    "admin.tripPricingSegmentAdd": "Προσθήκη τμήματος",
    "admin.tripPricingSegmentRemove": "Αφαίρεση τμήματος",
    "admin.tripPricingHotelEl": "Ξενοδοχείο (ελληνικά)",
    "admin.tripPricingHotelEn": "Ξενοδοχείο (αγγλικά)",
    "admin.tripPricingDouble": "Δίκλινο",
    "admin.tripPricingSingle": "Μονόκλινο",
    "admin.tripPricingTriple": "Τρίκλινο",
    "admin.tripPricingChild": "Παιδικό (2–12)",
    "admin.tripFlightDetailsSection": "Πληροφορίες πτήσεων",
    "admin.tripFlightDetailsHint":
      "Προαιρετικό: προσθέστε ένα ή περισσότερα ζεύγη αναχώρησης/επιστροφής (ελληνικά και αγγλικά). Εμφανίζονται στη σελίδα ταξιδιού όταν είναι ενεργό.",
    "admin.tripFlightDetailsEnable": "Εμφάνιση πληροφοριών πτήσεων στη σελίδα ταξιδιού",
    "admin.tripFlightDetailsOn": "Ενεργό",
    "admin.tripFlightDetailsOff": "Ανενεργό",
    "admin.tripFlightLegAdd": "Προσθήκη πτήσης",
    "admin.tripFlightLegLabel": "Σετ {n}",
    "admin.tripFlightLangEl": "Ελληνικά",
    "admin.tripFlightLangEn": "Αγγλικά",
    "admin.tripFlightLegRemove": "Αφαίρεση πτήσης",
    "admin.tripFlightLegsEmpty": "Δεν υπάρχουν ακόμα. Χρησιμοποιήστε Προσθήκη πτήσης.",
    "admin.tripFlightDepartureEl": "Αναχώρηση (ελληνικά)",
    "admin.tripFlightReturnEl": "Επιστροφή (ελληνικά)",
    "admin.tripFlightDepartureEn": "Αναχώρηση (αγγλικά)",
    "admin.tripFlightReturnEn": "Επιστροφή (αγγλικά)",
    "admin.tripFeatured": "Προτεινόμενο ταξίδι",
    "admin.tripProgramTimeline": "Πρόγραμμα (ανά ημέρα)",
    "admin.tripAddDay": "Προσθήκη ημέρας",
    "admin.tripRemoveDay": "Αφαίρεση ημέρας",
    "admin.tripDayNumber": "Ημέρα #",
    "admin.tripDayTitle": "Τίτλος ημέρας",
    "admin.tripDayDescription": "Περιγραφή ημέρας",
    "admin.tripIncludedEl": "Περιλαμβάνονται (ελληνικά)",
    "admin.tripTagsEl": "Ετικέτες (ελληνικά)",
    "admin.tripIncludedEn": "Περιλαμβάνονται (αγγλικά)",
    "admin.tripNotIncludedEl": "Δεν περιλαμβάνονται (ελληνικά)",
    "admin.tripNotIncludedEn": "Δεν περιλαμβάνονται (αγγλικά)",
    "admin.tripTagsEn": "Ετικέτες (αγγλικά)",
    "admin.tripArrayHint": "Πληκτρολογήστε και Enter",
    "admin.tripProgramMinDay": "Προσθέστε τουλάχιστον μία ημέρα στο πρόγραμμα.",
    "admin.tripProgramNeedsContent":
      "Συμπληρώστε τίτλο ή περιγραφή για τουλάχιστον μία ημέρα.",
    "admin.tripIncludedMin":
      "Προσθέστε τουλάχιστον ένα στοιχείο «περιλαμβάνονται».",
    "admin.inbox": "Εισερχόμενα",
    "admin.inquiry": "Αίτημα",
    "admin.from": "Από",
    "admin.trip": "Ταξίδι",
    "admin.message": "Μήνυμα",
    "admin.status": "Κατάσταση",
    "admin.internalNotes": "Εσωτερικές σημειώσεις",
    "admin.notesPlaceholder": "Ιδιωτικές σημειώσεις…",
    "admin.loginTitle": "Σύνδεση διαχειριστή",
    "admin.loginSubtitle": "Εισάγετε τα στοιχεία σας για πρόσβαση στον πίνακα.",
    "admin.email": "Email",
    "admin.password": "Κωδικός",
    "admin.signingIn": "Σύνδεση…",
    "admin.signIn": "Σύνδεση",
    "admin.unauthorizedToast":
      "Μη εξουσιοδοτημένος: απαιτείται ρόλος διαχειριστή",
    "admin.sessionExpiredToast": "Η συνεδρία σας έληξε. Συνδεθείτε ξανά.",
    "admin.forbiddenAccessToast":
      "Μη εξουσιοδοτημένη πρόσβαση. Έχετε αποσυνδεθεί.",
    "admin.signInFailed": "Η σύνδεση απέτυχε",
    "admin.close": "Κλείσιμο",
    "admin.activityFeed": "Χρονολόγιο",
    "admin.timelineCustomer": "Πελάτης",
    "admin.timelineSystem": "Σύστημα",
    "admin.timelineAdmin": "Διαχειριστής",
    "admin.timelineYou": "Εσείς",
    "admin.commentPlaceholder": "Γράψτε ένα σχόλιο ή επισυνάψτε αρχεία...",
    "admin.postComment": "Αποστολή σχολίου",
    "admin.postingComment": "Αποστολή…",
    "admin.commentPosted": "Το σχόλιο προστέθηκε",
    "admin.commentFailed": "Αποτυχία αποστολής σχολίου",
    "admin.statusSaved": "Η κατάσταση αποθηκεύτηκε",
    "admin.saveStatus": "Αποθήκευση κατάστασης",
    "admin.commentsLoadFailed": "Αποτυχία φόρτωσης σχολίων",
    "admin.timelineOlderAbove": "Παλιότερα μηνύματα πάνω",
    "admin.timelineNewerBelow": "Περισσότερα μηνύματα κάτω",
    "admin.editor.toolbar": "Μορφοποίηση",
    "admin.editor.bold": "Έντονα",
    "admin.editor.italic": "Πλάγια",
    "admin.editor.underline": "Υπογράμμιση",
    "admin.editor.bulletList": "Κουκκίδες",
    "admin.editor.orderedList": "Αρίθμηση",
    "admin.editor.link": "Σύνδεσμος",
    "admin.editor.linkPrompt": "Επικολλήστε ή πληκτρολογήστε URL",
    "admin.editor.attachFile": "Επισύναψη αρχείου",
    "admin.editor.attachUploaded": "Το αρχείο προστέθηκε",
    "admin.editor.attachFailed":
      "Η μεταφόρτωση απέτυχε. Παρακαλώ δοκιμάστε ξανά.",
    "admin.inquiryAttachmentDownload": "Λήψη",
    "admin.inquiryAttachmentLinkLoading": "Προετοιμασία συνδέσμου…",
    "admin.inquiryAttachmentDownloadFailed":
      "Δεν ήταν δυνατό το άνοιγμα του αρχείου. Δοκιμάστε ξανά.",
    "admin.inquiryAttachmentPreviewTitle": "Προεπισκόπηση",
    "admin.inquiryAttachmentPreviewTooltip": "Προεπισκόπηση",
    "admin.inquiryAttachmentPreviewDownloadAria": "Λήψη συνημμένου",
    "admin.inquiryAttachmentPreviewCloseAria": "Κλείσιμο προεπισκόπησης",
    "admin.inquiryAttachmentPreviewPrevAria": "Προηγούμενο συνημμένο",
    "admin.inquiryAttachmentPreviewNextAria": "Επόμενο συνημμένο",
    "admin.inquiryAttachmentPreviewLoadFailed":
      "Δεν ήταν δυνατή η φόρτωση της προεπισκόπησης.",
    "admin.inquiryAttachmentGalleryLabel": "Συνημμένα αρχεία",
    "admin.inquiryAttachmentPendingLabel": "Συνημμένα προς αποστολή",
    "admin.inquiryAttachmentRemove": "Αφαίρεση",
    "admin.inquiryAttachmentUploading": "Μεταφόρτωση…",
    "admin.inquiryAttachmentErrMaxFiles": "Μέχρι 5 αρχεία ανά σχόλιο.",
    "admin.inquiryAttachmentErrFileTooLarge": "Κάθε αρχείο έως 10 MB.",
    "admin.inquiryAttachmentErrTotalTooLarge":
      "Συνολικό μέγεθος συνημμένων έως 50 MB.",
    "admin.inquiryAttachmentAddMore": "Προσθήκη περισσότερων",
    "admin.inquiryAttachmentRemovePending": "Κατάργηση από την ουρά",
    "admin.inquiryAttachmentDeleteSaved": "Κατάργηση συνημμένου",
    "admin.inquiryAttachmentUploadProgress": "Πρόοδος μεταφόρτωσης",
    "admin.inquiryAttachmentUploadBatchFailed":
      "Η μεταφόρτωση απέτυχε. Δοκιμάστε ξανά.",
    "admin.inquiryAttachmentDeleteFailed":
      "Δεν ήταν δυνατή η κατάργηση του συνημμένου.",
    "admin.inquiryQuickPhone": "Επικοινώνησα τηλεφωνικά",
    "admin.inquiryQuickEmail": "Στάλθηκε email προσφοράς",
    "admin.inquiryQuickFollowUp": "Προγραμματίστηκε επανεπικοινωνία",
    "admin.copyMessage": "Αντιγραφή μηνύματος",
    "admin.copied": "Αντιγράφηκε",
    "admin.editor.fontSize": "Μέγεθος γραμματοσειράς",
    "admin.editor.sizeDefault": "Προεπιλογή",
    "admin.editor.sizeSmall": "Μικρό",
    "admin.editor.sizeNormal": "Κανονικό",
    "admin.editor.sizeLarge": "Μεγάλο",
    "admin.editor.sizeXl": "Πολύ μεγάλο",
    "admin.statusNew": "Νέο",
    "admin.statusContacted": "Σε επικοινωνία",
    "admin.statusResolved": "Ολοκληρώθηκε",
    "admin.statusSaveFailed": "Αποτυχία αποθήκευσης κατάστασης",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => readStoredLang() ?? "gr");

  const setLang = useCallback((next: Lang) => {
    setLangState(next);
    writeStoredLang(next);
  }, []);

  const t = (key: string) => translations[lang][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
