import { createContext, useContext, useState, type ReactNode } from "react";

export type Lang = "en" | "gr";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Navbar
    "nav.brand": "VALITSA",
    "nav.terms": "Terms & Conditions",
    "nav.daily": "Daily Trips",
    "nav.twoday": "2-Day Trips",
    "nav.internal": "Domestic Trips",
    "nav.external": "International Trips",
    "nav.contactBtn": "Contact",
    "nav.toggleLanguage": "Toggle language",
    "nav.toggleTheme": "Toggle theme",
    "nav.menu": "Menu",

    // Common
    "common.close": "Close",
    "common.scrollUp": "Scroll up",
    "common.scrollUpAria": "Scroll to top",

    // Contact Modal
    "contact.title": "Contact Us",
    "contact.callUs": "Call Us",
    "contact.whatsapp": "WhatsApp",
    "contact.whatsappDesc": "Chat with us instantly",
    "contact.viber": "Viber",
    "contact.viberDesc": "Message us on Viber",
    "contact.sendMessage": "Send a Message",
    "contact.sendMessageDesc": "Fill out the form and we'll get back to you",
    "contact.back": "Back",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.sendFailed": "Failed to send message. Please try again.",
    "contact.sent": "Message Sent!",
    "contact.sentDesc": "We'll get back to you within 24 hours.",

    "validation.required": "This field is required",
    "validation.emailInvalid": "Please enter a valid email address",
    "validation.phoneInvalid": "Please enter a valid phone number",

    // Hero
    "hero.label": "Luxury Travel, Redefined",
    "hero.title": "Discover Your Next Destination",
    "hero.subtitle":
      "Handcrafted journeys to the world's most extraordinary places. Every detail curated, every moment unforgettable.",
    "hero.cta": "View All Our Trips",
    "hero.alt": "Aerial view of a serene tropical coastline",

    // Featured
    "featured.label": "Curated Collections",
    "featured.title": "Featured Escapes",
    "featured.viewAll": "View all trips",

    // Trip Grid
    "grid.label": "Curated Collections",
    "grid.title": "Featured Escapes",
    "grid.all": "All",
    "grid.viewDetails": "View Details",

    // Trip Card Quick Links
    "card.moreDuration": "More {duration} Trips",
    "card.moreType": "More {type} Trips",
    "card.trip": "Trip",

    // Trip Detail
    "detail.startingFrom": "Starting from",
    "detail.expressInterest": "Express Your Interest",
    "detail.firstName": "First Name",
    "detail.lastName": "Last Name",
    "detail.email": "Email Address",
    "detail.mobile": "Mobile",
    "detail.message": "Tell us about your preferences...",
    "detail.sendInquiry": "Send Inquiry",
    "detail.sending": "Sending...",
    "detail.sendFailed": "Failed to send inquiry. Please try again.",
    "detail.inquirySent": "Inquiry Sent",
    "detail.inquiryMsg": "We'll be in touch within 24 hours.",
    "detail.description": "Description",
    "detail.tripNotes": "Notes",
    "detail.program": "Program",
    "detail.included": "Included",
    "detail.notIncluded": "Not included",
    "detail.galleryOpen": "Open photo gallery",
    "detail.galleryPrev": "Previous photo",
    "detail.galleryNext": "Next photo",
    "detail.galleryThumbPin": "Preview or select gallery photo",
    "detail.galleryCarouselRegion": "Trip photos",

    // Archive / Search Page
    "archive.title": "All Trips",
    "archive.resultsFound": "trips found",
    "archive.searchPlaceholder": "Search by title...",
    "archive.priceRange": "Price Range",
    "archive.specialFilters": "Travel Preferences",
    "archive.featuredPicks": "Top Picks",
    "archive.sortBy": "Sort By",
    "archive.sort.recommended": "Recommended",
    "archive.sort.priceAsc": "Lowest Price",
    "archive.sort.priceDesc": "Highest Price",
    "archive.sort.durationAsc": "Shortest Duration",
    "archive.duration": "Duration",
    "archive.days": "Days",
    "archive.continent": "Continent",
    "archive.country": "Country",
    "archive.departureCity": "Departure City",
    "archive.category": "Category",
    "archive.tripType": "Trip Type",
    "archive.all": "All",
    "archive.group": "Group Trips",
    "archive.individual": "Individual",
    "archive.more": "MORE",
    "archive.noResults": "No trips match your filters.",

    "trips.disabledSeoTitle": "Valitsa Travel",
    "trips.disabledSeoDescription":
      "Contact us for travel planning and inquiries.",
    "trips.disabledHeading": "Trips unavailable",
    "trips.disabledBody":
      "Our trip listings are not shown at the moment. Use the contact button in the menu and we will assist you.",
    "trips.disabledHomeLink": "Back to home",

    // Trip Types
    "tripType.Exotic": "Exotic",
    "tripType.Road Trip": "Road Trip",
    "tripType.Flight": "Flight",

    // Not Found
    "notFound.message": "Oops! Page not found",
    "notFound.backHome": "Return to Home",

    // Advanced Search
    "search.title": "Advanced Search",
    "search.destination": "Destination",
    "search.internal": "Internal",
    "search.external": "External",
    "search.duration": "Duration (Days)",
    "search.category": "Category",
    "search.cultural": "Cultural",
    "search.adventure": "Adventure",
    "search.religious": "Religious",
    "search.wellness": "Wellness",
    "search.wildlife": "Wildlife",
    "search.expedition": "Expedition",
    "search.priceRange": "Price Range",
    "search.transport": "Transport Mode",
    "search.bus": "Bus",
    "search.plane": "Plane",
    "search.ship": "Ship",
    "search.apply": "Apply Filters",
    "search.reset": "Reset Filters",
    "search.filters": "Filters",

    // Countries
    "country.Greece": "Greece",
    "country.Italy": "Italy",
    "country.Japan": "Japan",
    "country.Iceland": "Iceland",
    "country.Switzerland": "Switzerland",
    "country.Tanzania": "Tanzania",
    "country.Chile": "Chile",
    "country.France": "France",
    "country.Peru": "Peru",
    "country.Egypt": "Egypt",
    "country.USA": "USA",

    // Continents
    "continent.Europe": "Europe",
    "continent.Asia": "Asia",
    "continent.Africa": "Africa",
    "continent.North America": "North America",
    "continent.South America": "South America",
    "continent.Other": "Other",

    // Footer
    "footer.rights": "© 2026 Valitsa Travel. All rights reserved.",

    // Admin
    "admin.language": "Language",
    "admin.openMenu": "Open menu",
    "admin.signOut": "Sign out",
    "admin.dashboardTitle": "Dashboard",
    "admin.dashboardSubtitle": "Overview of your catalog and inquiries.",
    "admin.widgetTrips": "Trips",
    "admin.widgetTripsHint": "Open trip catalog",
    "admin.widgetInquiries": "Inquiries",
    "admin.widgetInquiriesHint": "Open inquiry inbox",
    "admin.tripsTitle": "Trips",
    "admin.tripsSubtitle": "Manage listings and analytics.",
    "admin.leadsTitle": "Inquiries",
    "admin.leadsSubtitle": "Inquiries and follow-ups.",
    "admin.catalog": "Catalog",
    "admin.name": "Name",
    "admin.clicks": "Clicks",
    "admin.forms": "Interested",
    "admin.featured": "Featured",
    "admin.untitled": "Untitled",
    "admin.tripTablePhoto": "Image",
    "admin.tripTableEdit": "Edit",
    "admin.tripTableDelete": "Delete",
    "admin.tripDeleteConfirmTitle": "Are you sure?",
    "admin.tripDeleteConfirmMessage":
      "This action cannot be undone. The trip will be permanently deleted.",
    "admin.tripDeleteCancel": "Cancel",
    "admin.tripDeleteConfirm": "Delete",
    "admin.tripDeleted": "The trip was deleted successfully.",
    "admin.tripDeleteFailed": "Could not delete trip.",
    "admin.editTrip": "Edit trip",
    "admin.addTrip": "Add trip",
    "admin.editTripDesc":
      "English and Greek fields; rich text is stored as HTML.",
    "admin.titleEn": "Title (English)",
    "admin.titleEl": "Title (Greek)",
    "admin.heroImage": "Hero image",
    "admin.mainPhotoFeatured": "Main Photo (Featured)",
    "admin.galleryPhotos": "Gallery Photos",
    "admin.galleryPhotosHint":
      "Up to four additional images, shown in order. Use the X on a thumbnail to remove it.",
    "admin.tripGalleryDropHint": "Drop or select 1–4 images",
    "admin.tripGalleryRemove": "Remove from gallery",
    "admin.tripGalleryRemoveShort": "Remove",
    "admin.tripGalleryDownload": "Download",
    "admin.tripGalleryPreviewOpen": "Open full preview",
    "admin.tripGalleryPreviewClose": "Close preview",
    "admin.tripGalleryPreviewTitle": "Gallery image",
    "admin.tripGalleryEmptySlot": "Empty",
    "admin.descriptionEn": "Description (English)",
    "admin.descriptionEl": "Description (Greek)",
    "admin.tripNotesEn": "Trip notes (English)",
    "admin.tripNotesEl": "Trip notes (Greek)",
    "admin.programEn": "Program (English)",
    "admin.programEl": "Program (Greek)",
    "admin.includedEn": "Included (English)",
    "admin.includedEl": "Included (Greek)",
    "admin.cancel": "Cancel",
    "admin.save": "Save",
    "admin.saving": "Saving…",
    "admin.tripSaved": "Trip saved",
    "admin.tripSaveFailed": "Could not save trip",
    "admin.tabGreek": "Ελληνικά",
    "admin.tabEnglish": "English",
    "admin.tripSinglePhotoHint":
      "Only one main (featured) photo per trip. Remove it to upload a different one.",
    "admin.tripRemoveImage": "Remove image",
    "admin.tripFieldRequired": "This field is required.",
    "admin.tripRichFieldRequired": "This section cannot be empty.",
    "admin.tripCommonSettings": "Pricing and visibility",
    "admin.tripStatus": "Trip status",
    "admin.tripStatusActive": "Active",
    "admin.tripStatusInactive": "Inactive",
    "admin.tripEnableEnglish": "Enable English translation",
    "admin.tripEnableEnglishHint":
      "When off, English fields are ignored. When on, all English fields are required like Greek.",
    "admin.tripLocationEl": "Location (Greek)",
    "admin.tripCountryEl": "Country (Greek)",
    "admin.tripTypeEl": "Type (Greek)",
    "admin.tripCategoryEl": "Category (Greek)",
    "admin.tripTransportEl": "Transport (Greek)",
    "admin.tripDateRangeEl": "Date range (Greek)",
    "admin.tripDepartureCityEl": "Departure city (Greek)",
    "admin.tripLocationEn": "Location (English)",
    "admin.tripCountryEn": "Country (English)",
    "admin.tripTypeEn": "Type (English)",
    "admin.tripCategoryEn": "Category (English)",
    "admin.tripTransportEn": "Transport (English)",
    "admin.tripDateRangeEn": "Date range (English)",
    "admin.tripDepartureCityEn": "Departure city (English)",
    "admin.tripProgramDays": "Days",
    "admin.tripDaysPlaceholder": "e.g. 1, 1-2, 4-7",
    "admin.tripDaysInvalid": "Enter a day or range like 1, 1-2, or 4-7.",
    "admin.transportMenu": "Transport modes",
    "admin.transportPlaceholder": "Select transport modes",
    "admin.tripPriceNum": "Price",
    "admin.tripDurationDays": "Duration (days)",
    "admin.tripFeatured": "Featured trip",
    "admin.tripProgramTimeline": "Itinerary (by day)",
    "admin.tripAddDay": "Add day",
    "admin.tripRemoveDay": "Remove day",
    "admin.tripDayNumber": "Day #",
    "admin.tripDayTitle": "Day title",
    "admin.tripDayDescription": "Day description",
    "admin.tripIncludedEl": "What's included (Greek)",
    "admin.tripTagsEl": "Tags (Greek)",
    "admin.tripIncludedEn": "What's included (English)",
    "admin.tripNotIncludedEl": "Not included (Greek)",
    "admin.tripNotIncludedEn": "Not included (English)",
    "admin.tripTagsEn": "Tags (English)",
    "admin.tripArrayHint": "Type and press Enter",
    "admin.tripProgramMinDay": "Add at least one itinerary day.",
    "admin.tripProgramNeedsContent": "Add a title or description for at least one day.",
    "admin.tripIncludedMin": "Add at least one included item.",
    "admin.inbox": "Inbox",
    "admin.inquiry": "Inquiry",
    "admin.from": "From",
    "admin.trip": "Trip",
    "admin.message": "Message",
    "admin.status": "Status",
    "admin.internalNotes": "Internal notes",
    "admin.notesPlaceholder": "Private notes…",
    "admin.loginTitle": "Admin sign in",
    "admin.loginSubtitle": "Enter your credentials to access the dashboard.",
    "admin.email": "Email",
    "admin.password": "Password",
    "admin.signingIn": "Signing in…",
    "admin.signIn": "Sign in",
    "admin.unauthorizedToast": "Unauthorized: admin access required",
    "admin.sessionExpiredToast": "Your session has expired. Please sign in again.",
    "admin.forbiddenAccessToast": "Access denied. Admin privileges are required. You have been signed out.",
    "admin.signInFailed": "Sign in failed",
    "admin.close": "Close",
    "admin.activityFeed": "Activity",
    "admin.timelineCustomer": "Customer",
    "admin.timelineSystem": "System",
    "admin.timelineAdmin": "Admin",
    "admin.timelineYou": "You",
    "admin.commentPlaceholder": "Write an internal comment…",
    "admin.postComment": "Post comment",
    "admin.postingComment": "Posting…",
    "admin.commentPosted": "Comment added",
    "admin.commentFailed": "Could not post comment",
    "admin.statusSaved": "Status saved",
    "admin.saveStatus": "Save status",
    "admin.commentsLoadFailed": "Could not load comments",
    "admin.timelineOlderAbove": "Older messages above",
    "admin.timelineNewerBelow": "More messages below",
    "admin.editor.toolbar": "Formatting",
    "admin.editor.bold": "Bold",
    "admin.editor.italic": "Italic",
    "admin.editor.underline": "Underline",
    "admin.editor.bulletList": "Bullet list",
    "admin.editor.orderedList": "Numbered list",
    "admin.editor.link": "Link",
    "admin.editor.linkPrompt": "Paste or type a URL",
    "admin.editor.attachFile": "Attach file",
    "admin.editor.attachUploaded": "Attachment added",
    "admin.editor.attachFailed": "Upload failed. Please try again.",
    "admin.inquiryAttachmentDownload": "Download",
    "admin.inquiryAttachmentLinkLoading": "Preparing link…",
    "admin.inquiryAttachmentDownloadFailed": "Could not open the file. Please try again.",
    "admin.inquiryAttachmentPreviewTitle": "Preview",
    "admin.inquiryAttachmentPreviewTooltip": "Preview",
    "admin.inquiryAttachmentPreviewDownloadAria": "Download attachment",
    "admin.inquiryAttachmentPreviewCloseAria": "Close preview",
    "admin.inquiryAttachmentPreviewPrevAria": "Previous attachment",
    "admin.inquiryAttachmentPreviewNextAria": "Next attachment",
    "admin.inquiryAttachmentPreviewLoadFailed": "Could not load the preview.",
    "admin.inquiryAttachmentGalleryLabel": "Attached files",
    "admin.inquiryAttachmentPendingLabel": "Pending attachments",
    "admin.inquiryAttachmentRemove": "Remove",
    "admin.inquiryAttachmentUploading": "Uploading…",
    "admin.inquiryAttachmentErrMaxFiles": "You can attach up to 5 files per comment.",
    "admin.inquiryAttachmentErrFileTooLarge": "Each file must be at most 10 MB.",
    "admin.inquiryAttachmentErrTotalTooLarge": "Total size of attachments must be at most 50 MB.",
    "admin.inquiryAttachmentAddMore": "Add more files",
    "admin.inquiryAttachmentRemovePending": "Remove from queue",
    "admin.inquiryAttachmentDeleteSaved": "Delete attachment",
    "admin.inquiryAttachmentUploadProgress": "Upload progress",
    "admin.inquiryAttachmentUploadBatchFailed": "Upload failed. Please try again.",
    "admin.inquiryAttachmentDeleteFailed": "Could not delete the attachment.",
    "admin.inquiryQuickPhone": "Called by phone",
    "admin.inquiryQuickEmail": "Offer email sent",
    "admin.inquiryQuickFollowUp": "Follow-up scheduled",
    "admin.copyMessage": "Copy message",
    "admin.copied": "Copied",
    "admin.editor.fontSize": "Font size",
    "admin.editor.sizeDefault": "Default",
    "admin.editor.sizeSmall": "Small",
    "admin.editor.sizeNormal": "Normal",
    "admin.editor.sizeLarge": "Large",
    "admin.editor.sizeXl": "Extra large",
    "admin.statusNew": "New",
    "admin.statusContacted": "Contacted",
    "admin.statusResolved": "Resolved",
    "admin.statusSaveFailed": "Could not save status",
  },
  gr: {
    // Navbar
    "nav.brand": "VALITSA",
    "nav.terms": "Όροι & Προϋποθέσεις",
    "nav.daily": "Ημερήσιες Εκδρομές",
    "nav.twoday": "2ήμερες Εκδρομές",
    "nav.internal": "Εκδρομές Εσωτερικού",
    "nav.external": "Εκδρομές Εξωτερικού",
    "nav.contactBtn": "Επικοινωνία",
    "nav.toggleLanguage": "Αλλαγή γλώσσας",
    "nav.toggleTheme": "Αλλαγή θέματος",
    "nav.menu": "Μενού",

    // Common
    "common.close": "Κλείσιμο",
    "common.scrollUp": "Επιστροφή στην κορυφή",
    "common.scrollUpAria": "Κύλιση στην κορυφή",

    // Contact Modal
    "contact.title": "Επικοινωνία",
    "contact.callUs": "Καλέστε μας",
    "contact.whatsapp": "WhatsApp",
    "contact.whatsappDesc": "Συνομιλήστε μαζί μας άμεσα",
    "contact.viber": "Viber",
    "contact.viberDesc": "Στείλτε μας μήνυμα στο Viber",
    "contact.sendMessage": "Στείλτε μήνυμα",
    "contact.sendMessageDesc":
      "Συμπληρώστε τη φόρμα και θα επικοινωνήσουμε μαζί σας",
    "contact.back": "Πίσω",
    "contact.send": "Αποστολή",
    "contact.sending": "Αποστολή...",
    "contact.sendFailed": "Αποτυχία αποστολής. Προσπαθήστε ξανά.",
    "contact.sent": "Το μήνυμα στάλθηκε!",
    "contact.sentDesc": "Θα επικοινωνήσουμε μαζί σας εντός 24 ωρών.",

    "validation.required": "Το πεδίο είναι υποχρεωτικό",
    "validation.emailInvalid": "Εισάγετε έγκυρη διεύθυνση email",
    "validation.phoneInvalid": "Εισάγετε έγκυρο αριθμό τηλεφώνου",

    // Hero
    "hero.label": "Πολυτελή Ταξίδια, Ξανά",
    "hero.title": "Ανακαλύψτε τον Επόμενο Προορισμό σας",
    "hero.subtitle":
      "Χειροποίητα ταξίδια στα πιο εξαιρετικά μέρη του κόσμου. Κάθε λεπτομέρεια επιμελημένη, κάθε στιγμή αξέχαστη.",
    "hero.cta": "Δείτε όλα τα ταξίδια μας",
    "hero.alt": "Εναέρια θέα σε ήρεμη τροπική ακτογραμμή",

    // Featured
    "featured.label": "Επιλεγμένες Συλλογές",
    "featured.title": "Κορυφαίες Αποδράσεις",
    "featured.viewAll": "Δείτε όλα τα ταξίδια",

    // Trip Grid
    "grid.label": "Επιλεγμένες Συλλογές",
    "grid.title": "Κορυφαίες Αποδράσεις",
    "grid.all": "Όλα",
    "grid.viewDetails": "Λεπτομέρειες",

    // Trip Card Quick Links
    "card.moreDuration": "Περισσότερα {duration} Ταξίδια",
    "card.moreType": "Περισσότερα {type} Ταξίδια",
    "card.trip": "Ταξίδι",

    // Trip Detail
    "detail.startingFrom": "Από",
    "detail.expressInterest": "Εκδηλώστε Ενδιαφέρον",
    "detail.firstName": "Όνομα",
    "detail.lastName": "Επώνυμο",
    "detail.email": "Email",
    "detail.mobile": "Κινητό",
    "detail.message": "Πείτε μας τις προτιμήσεις σας...",
    "detail.sendInquiry": "Αποστολή",
    "detail.sending": "Αποστολή...",
    "detail.sendFailed": "Αποτυχία αποστολής αιτήματος. Προσπαθήστε ξανά.",
    "detail.inquirySent": "Το αίτημα στάλθηκε",
    "detail.inquiryMsg": "Θα επικοινωνήσουμε εντός 24 ωρών.",
    "detail.description": "Περιγραφή",
    "detail.tripNotes": "Σημειώσεις",
    "detail.program": "Πρόγραμμα",
    "detail.included": "Περιλαμβάνονται",
    "detail.notIncluded": "Δεν περιλαμβάνονται",
    "detail.galleryOpen": "Άνοιγμα συλλογής φωτογραφιών",
    "detail.galleryPrev": "Προηγούμενη φωτογραφία",
    "detail.galleryNext": "Επόμενη φωτογραφία",
    "detail.galleryThumbPin": "Προεπισκόπηση ή επιλογή φωτογραφίας συλλογής",
    "detail.galleryCarouselRegion": "Φωτογραφίες ταξιδιού",

    // Archive / Search Page
    "archive.title": "Όλα τα Ταξίδια",
    "archive.resultsFound": "ταξίδια βρέθηκαν",
    "archive.searchPlaceholder": "Αναζήτηση με τίτλο...",
    "archive.priceRange": "Εύρος Τιμής",
    "archive.specialFilters": "Προτιμήσεις Ταξιδιού",
    "archive.featuredPicks": "Κορυφαίες Επιλογές",
    "archive.sortBy": "Ταξινόμηση",
    "archive.sort.recommended": "Προτεινόμενα",
    "archive.sort.priceAsc": "Χαμηλότερη Τιμή",
    "archive.sort.priceDesc": "Υψηλότερη Τιμή",
    "archive.sort.durationAsc": "Μικρότερη Διάρκεια",
    "archive.duration": "Διάρκεια",
    "archive.days": "Ημέρες",
    "archive.continent": "Ήπειρος",
    "archive.country": "Χώρα",
    "archive.departureCity": "Πόλη Αναχώρησης",
    "archive.category": "Κατηγορία",
    "archive.tripType": "Τύπος Ταξιδιού",
    "archive.all": "Όλα",
    "archive.group": "Ομαδικά Ταξίδια",
    "archive.individual": "Ατομικά",
    "archive.more": "ΠΕΡΙΣΣΟΤΕΡΑ",
    "archive.noResults": "Δεν βρέθηκαν ταξίδια με αυτά τα φίλτρα.",

    "trips.disabledSeoTitle": "Valitsa Travel",
    "trips.disabledSeoDescription":
      "Επικοινωνήστε μαζί μας για οργάνωση ταξιδιών και ερωτήσεις.",
    "trips.disabledHeading": "Τα ταξίδια δεν είναι διαθέσιμα",
    "trips.disabledBody":
      "Η λίστα ταξιδιών δεν εμφανίζεται αυτή τη στιγμή. Χρησιμοποιήστε το κουμπί επικοινωνίας στο μενού και θα σας βοηθήσουμε.",
    "trips.disabledHomeLink": "Επιστροφή στην αρχική",

    // Trip Types
    "tripType.Exotic": "Εξωτικό",
    "tripType.Road Trip": "Οδικό",
    "tripType.Flight": "Αεροπορικό",

    // Not Found
    "notFound.message": "Ουπς! Η σελίδα δεν βρέθηκε",
    "notFound.backHome": "Επιστροφή στην Αρχική",

    // Advanced Search
    "search.title": "Σύνθετη Αναζήτηση",
    "search.destination": "Προορισμός",
    "search.internal": "Εσωτερικό",
    "search.external": "Εξωτερικό",
    "search.duration": "Διάρκεια (Ημέρες)",
    "search.category": "Κατηγορία",
    "search.cultural": "Πολιτιστικό",
    "search.adventure": "Περιπέτεια",
    "search.religious": "Θρησκευτικό",
    "search.wellness": "Ευεξία",
    "search.wildlife": "Άγρια Ζωή",
    "search.expedition": "Εξερεύνηση",
    "search.priceRange": "Εύρος Τιμής",
    "search.transport": "Μέσο Μεταφοράς",
    "search.bus": "Λεωφορείο",
    "search.plane": "Αεροπλάνο",
    "search.ship": "Πλοίο",
    "search.apply": "Εφαρμογή",
    "search.reset": "Επαναφορά Φίλτρων",
    "search.filters": "Φίλτρα",

    // Countries
    "country.Greece": "Ελλάδα",
    "country.Italy": "Ιταλία",
    "country.Japan": "Ιαπωνία",
    "country.Iceland": "Ισλανδία",
    "country.Switzerland": "Ελβετία",
    "country.Tanzania": "Τανζανία",
    "country.Chile": "Χιλή",
    "country.France": "Γαλλία",
    "country.Peru": "Περού",
    "country.Egypt": "Αίγυπτος",
    "country.USA": "ΗΠΑ",

    // Continents
    "continent.Europe": "Ευρώπη",
    "continent.Asia": "Ασία",
    "continent.Africa": "Αφρική",
    "continent.North America": "Βόρεια Αμερική",
    "continent.South America": "Νότια Αμερική",
    "continent.Other": "Άλλη",

    // Footer
    "footer.rights": "© 2026 Valitsa Travel. Με επιφύλαξη παντός δικαιώματος.",

    // Admin
    "admin.language": "Γλώσσα",
    "admin.openMenu": "Άνοιγμα μενού",
    "admin.signOut": "Αποσύνδεση",
    "admin.dashboardTitle": "Πίνακας ελέγχου",
    "admin.dashboardSubtitle": "Επισκόπηση καταλόγου και αιτημάτων.",
    "admin.widgetTrips": "Ταξίδια",
    "admin.widgetTripsHint": "Άνοιγμα καταλόγου ταξιδιών",
    "admin.widgetInquiries": "Αιτήματα",
    "admin.widgetInquiriesHint": "Άνοιγμα εισερχομένων",
    "admin.tripsTitle": "Ταξίδια",
    "admin.tripsSubtitle": "Διαχείριση καταχωρίσεων και αναλυτικών.",
    "admin.leadsTitle": "Αιτήματα",
    "admin.leadsSubtitle": "Αιτήματα και παρακολούθηση.",
    "admin.catalog": "Κατάλογος",
    "admin.name": "Όνομα",
    "admin.clicks": "Κλικ",
    "admin.forms": "Ενδιαφερόμενοι",
    "admin.featured": "Προτεινόμενο",
    "admin.untitled": "Χωρίς τίτλο",
    "admin.tripTablePhoto": "Φωτογραφία",
    "admin.tripTableEdit": "Επεξεργασία",
    "admin.tripTableDelete": "Διαγραφή",
    "admin.tripDeleteConfirmTitle": "Είστε σίγουροι;",
    "admin.tripDeleteConfirmMessage":
      "Αυτή η ενέργεια δεν μπορεί να αναιρεθεί. Το ταξίδι θα διαγραφεί οριστικά.",
    "admin.tripDeleteCancel": "Ακύρωση",
    "admin.tripDeleteConfirm": "Διαγραφή",
    "admin.tripDeleted": "Το ταξίδι διαγράφηκε με επιτυχία.",
    "admin.tripDeleteFailed": "Αποτυχία διαγραφής ταξιδιού.",
    "admin.editTrip": "Επεξεργασία ταξιδιού",
    "admin.addTrip": "Προσθήκη Ταξιδιού",
    "admin.editTripDesc":
      "Πεδία στα αγγλικά και ελληνικά· το πλούσιο κείμενο αποθηκεύεται ως HTML.",
    "admin.titleEn": "Τίτλος (αγγλικά)",
    "admin.titleEl": "Τίτλος (ελληνικά)",
    "admin.heroImage": "Κύρια εικόνα",
    "admin.mainPhotoFeatured": "Κύρια φωτογραφία (προβεβλημένη)",
    "admin.galleryPhotos": "Φωτογραφίες συλλογής",
    "admin.galleryPhotosHint":
      "Έως τέσσερις επιπλέον εικόνες, με τη σειρά. Χρησιμοποιήστε το X για αφαίρεση.",
    "admin.tripGalleryDropHint": "Αποθέστε ή επιλέξτε έως 4 εικόνες",
    "admin.tripGalleryRemove": "Αφαίρεση από τη συλλογή",
    "admin.tripGalleryRemoveShort": "Αφαίρεση",
    "admin.tripGalleryDownload": "Λήψη",
    "admin.tripGalleryPreviewOpen": "Πλήρης προεπισκόπηση",
    "admin.tripGalleryPreviewClose": "Κλείσιμο προεπισκόπησης",
    "admin.tripGalleryPreviewTitle": "Εικόνα συλλογής",
    "admin.tripGalleryEmptySlot": "Κενό",
    "admin.descriptionEn": "Περιγραφή (αγγλικά)",
    "admin.descriptionEl": "Περιγραφή (ελληνικά)",
    "admin.tripNotesEn": "Σημειώσεις ταξιδιού (αγγλικά)",
    "admin.tripNotesEl": "Σημειώσεις ταξιδιού (ελληνικά)",
    "admin.programEn": "Πρόγραμμα (αγγλικά)",
    "admin.programEl": "Πρόγραμμα (ελληνικά)",
    "admin.includedEn": "Περιλαμβάνονται (αγγλικά)",
    "admin.includedEl": "Περιλαμβάνονται (ελληνικά)",
    "admin.cancel": "Ακύρωση",
    "admin.save": "Αποθήκευση",
    "admin.saving": "Αποθήκευση…",
    "admin.tripSaved": "Το ταξίδι αποθηκεύτηκε",
    "admin.tripSaveFailed": "Αποτυχία αποθήκευσης ταξιδιού",
    "admin.tabGreek": "Ελληνικά",
    "admin.tabEnglish": "English",
    "admin.tripSinglePhotoHint":
      "Μόνο μία κύρια (προβεβλημένη) φωτογραφία ανά ταξίδι. Αφαιρέστε την για να ανεβάσετε άλλη.",
    "admin.tripRemoveImage": "Αφαίρεση εικόνας",
    "admin.tripFieldRequired": "Υποχρεωτικό πεδίο.",
    "admin.tripRichFieldRequired": "Αυτή η ενότητα δεν μπορεί να είναι κενή.",
    "admin.tripCommonSettings": "Τιμολόγηση και εμφάνιση",
    "admin.tripStatus": "Κατάσταση ταξιδιού",
    "admin.tripStatusActive": "Ενεργό",
    "admin.tripStatusInactive": "Ανενεργό",
    "admin.tripEnableEnglish": "Ενεργοποίηση αγγλικής μετάφρασης",
    "admin.tripEnableEnglishHint":
      "Όταν είναι ανενεργό, τα αγγλικά πεδία αγνοούνται. Όταν είναι ενεργό, όλα τα αγγλικά πεδία είναι υποχρεωτικά όπως τα ελληνικά.",
    "admin.tripLocationEl": "Τοποθεσία (ελληνικά)",
    "admin.tripCountryEl": "Χώρα (ελληνικά)",
    "admin.tripTypeEl": "Τύπος (ελληνικά)",
    "admin.tripCategoryEl": "Κατηγορία (ελληνικά)",
    "admin.tripTransportEl": "Μεταφορά (ελληνικά)",
    "admin.tripDateRangeEl": "Χρονικό διάστημα (ελληνικά)",
    "admin.tripDepartureCityEl": "Πόλη αναχώρησης (ελληνικά)",
    "admin.tripLocationEn": "Τοποθεσία (αγγλικά)",
    "admin.tripCountryEn": "Χώρα (αγγλικά)",
    "admin.tripTypeEn": "Τύπος (αγγλικά)",
    "admin.tripCategoryEn": "Κατηγορία (αγγλικά)",
    "admin.tripTransportEn": "Μεταφορά (αγγλικά)",
    "admin.tripDateRangeEn": "Χρονικό διάστημα (αγγλικά)",
    "admin.tripDepartureCityEn": "Πόλη αναχώρησης (αγγλικά)",
    "admin.tripProgramDays": "Ημέρες",
    "admin.tripDaysPlaceholder": "π.χ. 1, 1-2, 4-7",
    "admin.tripDaysInvalid": "Χρησιμοποιήστε ημέρα ή εύρος όπως 1, 1-2 ή 4-7.",
    "admin.transportMenu": "Μέσα μεταφοράς",
    "admin.transportPlaceholder": "Επιλέξτε μέσα μεταφοράς",
    "admin.tripPriceNum": "Τιμή",
    "admin.tripDurationDays": "Διάρκεια (ημέρες)",
    "admin.tripFeatured": "Προτεινόμενο ταξίδι",
    "admin.tripProgramTimeline": "Πρόγραμμα (ανά ημέρα)",
    "admin.tripAddDay": "Προσθήκη ημέρας",
    "admin.tripRemoveDay": "Αφαίρεση ημέρας",
    "admin.tripDayNumber": "Ημέρα #",
    "admin.tripDayTitle": "Τίτλος ημέρας",
    "admin.tripDayDescription": "Περιγραφή ημέρας",
    "admin.tripIncludedEl": "Περιλαμβάνονται (ελληνικά)",
    "admin.tripTagsEl": "Ετικέτες (ελληνικά)",
    "admin.tripIncludedEn": "Περιλαμβάνονται (αγγλικά)",
    "admin.tripNotIncludedEl": "Δεν περιλαμβάνονται (ελληνικά)",
    "admin.tripNotIncludedEn": "Δεν περιλαμβάνονται (αγγλικά)",
    "admin.tripTagsEn": "Ετικέτες (αγγλικά)",
    "admin.tripArrayHint": "Πληκτρολογήστε και Enter",
    "admin.tripProgramMinDay": "Προσθέστε τουλάχιστον μία ημέρα στο πρόγραμμα.",
    "admin.tripProgramNeedsContent": "Συμπληρώστε τίτλο ή περιγραφή για τουλάχιστον μία ημέρα.",
    "admin.tripIncludedMin": "Προσθέστε τουλάχιστον ένα στοιχείο «περιλαμβάνονται».",
    "admin.inbox": "Εισερχόμενα",
    "admin.inquiry": "Αίτημα",
    "admin.from": "Από",
    "admin.trip": "Ταξίδι",
    "admin.message": "Μήνυμα",
    "admin.status": "Κατάσταση",
    "admin.internalNotes": "Εσωτερικές σημειώσεις",
    "admin.notesPlaceholder": "Ιδιωτικές σημειώσεις…",
    "admin.loginTitle": "Σύνδεση διαχειριστή",
    "admin.loginSubtitle": "Εισάγετε τα στοιχεία σας για πρόσβαση στον πίνακα.",
    "admin.email": "Email",
    "admin.password": "Κωδικός",
    "admin.signingIn": "Σύνδεση…",
    "admin.signIn": "Σύνδεση",
    "admin.unauthorizedToast":
      "Μη εξουσιοδοτημένος: απαιτείται ρόλος διαχειριστή",
    "admin.sessionExpiredToast":
      "Η συνεδρία σας έληξε. Συνδεθείτε ξανά.",
    "admin.forbiddenAccessToast":
      "Μη εξουσιοδοτημένη πρόσβαση. Έχετε αποσυνδεθεί.",
    "admin.signInFailed": "Η σύνδεση απέτυχε",
    "admin.close": "Κλείσιμο",
    "admin.activityFeed": "Χρονολόγιο",
    "admin.timelineCustomer": "Πελάτης",
    "admin.timelineSystem": "Σύστημα",
    "admin.timelineAdmin": "Διαχειριστής",
    "admin.timelineYou": "Εσείς",
    "admin.commentPlaceholder": "Γράψτε ένα σχόλιο ή επισυνάψτε αρχεία...",
    "admin.postComment": "Αποστολή σχολίου",
    "admin.postingComment": "Αποστολή…",
    "admin.commentPosted": "Το σχόλιο προστέθηκε",
    "admin.commentFailed": "Αποτυχία αποστολής σχολίου",
    "admin.statusSaved": "Η κατάσταση αποθηκεύτηκε",
    "admin.saveStatus": "Αποθήκευση κατάστασης",
    "admin.commentsLoadFailed": "Αποτυχία φόρτωσης σχολίων",
    "admin.timelineOlderAbove": "Παλιότερα μηνύματα πάνω",
    "admin.timelineNewerBelow": "Περισσότερα μηνύματα κάτω",
    "admin.editor.toolbar": "Μορφοποίηση",
    "admin.editor.bold": "Έντονα",
    "admin.editor.italic": "Πλάγια",
    "admin.editor.underline": "Υπογράμμιση",
    "admin.editor.bulletList": "Κουκκίδες",
    "admin.editor.orderedList": "Αρίθμηση",
    "admin.editor.link": "Σύνδεσμος",
    "admin.editor.linkPrompt": "Επικολλήστε ή πληκτρολογήστε URL",
    "admin.editor.attachFile": "Επισύναψη αρχείου",
    "admin.editor.attachUploaded": "Το αρχείο προστέθηκε",
    "admin.editor.attachFailed": "Η μεταφόρτωση απέτυχε. Παρακαλώ δοκιμάστε ξανά.",
    "admin.inquiryAttachmentDownload": "Λήψη",
    "admin.inquiryAttachmentLinkLoading": "Προετοιμασία συνδέσμου…",
    "admin.inquiryAttachmentDownloadFailed": "Δεν ήταν δυνατό το άνοιγμα του αρχείου. Δοκιμάστε ξανά.",
    "admin.inquiryAttachmentPreviewTitle": "Προεπισκόπηση",
    "admin.inquiryAttachmentPreviewTooltip": "Προεπισκόπηση",
    "admin.inquiryAttachmentPreviewDownloadAria": "Λήψη συνημμένου",
    "admin.inquiryAttachmentPreviewCloseAria": "Κλείσιμο προεπισκόπησης",
    "admin.inquiryAttachmentPreviewPrevAria": "Προηγούμενο συνημμένο",
    "admin.inquiryAttachmentPreviewNextAria": "Επόμενο συνημμένο",
    "admin.inquiryAttachmentPreviewLoadFailed": "Δεν ήταν δυνατή η φόρτωση της προεπισκόπησης.",
    "admin.inquiryAttachmentGalleryLabel": "Συνημμένα αρχεία",
    "admin.inquiryAttachmentPendingLabel": "Συνημμένα προς αποστολή",
    "admin.inquiryAttachmentRemove": "Αφαίρεση",
    "admin.inquiryAttachmentUploading": "Μεταφόρτωση…",
    "admin.inquiryAttachmentErrMaxFiles": "Μέχρι 5 αρχεία ανά σχόλιο.",
    "admin.inquiryAttachmentErrFileTooLarge": "Κάθε αρχείο έως 10 MB.",
    "admin.inquiryAttachmentErrTotalTooLarge": "Συνολικό μέγεθος συνημμένων έως 50 MB.",
    "admin.inquiryAttachmentAddMore": "Προσθήκη περισσότερων",
    "admin.inquiryAttachmentRemovePending": "Κατάργηση από την ουρά",
    "admin.inquiryAttachmentDeleteSaved": "Κατάργηση συνημμένου",
    "admin.inquiryAttachmentUploadProgress": "Πρόοδος μεταφόρτωσης",
    "admin.inquiryAttachmentUploadBatchFailed": "Η μεταφόρτωση απέτυχε. Δοκιμάστε ξανά.",
    "admin.inquiryAttachmentDeleteFailed": "Δεν ήταν δυνατή η κατάργηση του συνημμένου.",
    "admin.inquiryQuickPhone": "Επικοινώνησα τηλεφωνικά",
    "admin.inquiryQuickEmail": "Στάλθηκε email προσφοράς",
    "admin.inquiryQuickFollowUp": "Προγραμματίστηκε επανεπικοινωνία",
    "admin.copyMessage": "Αντιγραφή μηνύματος",
    "admin.copied": "Αντιγράφηκε",
    "admin.editor.fontSize": "Μέγεθος γραμματοσειράς",
    "admin.editor.sizeDefault": "Προεπιλογή",
    "admin.editor.sizeSmall": "Μικρό",
    "admin.editor.sizeNormal": "Κανονικό",
    "admin.editor.sizeLarge": "Μεγάλο",
    "admin.editor.sizeXl": "Πολύ μεγάλο",
    "admin.statusNew": "Νέο",
    "admin.statusContacted": "Σε επικοινωνία",
    "admin.statusResolved": "Ολοκληρώθηκε",
    "admin.statusSaveFailed": "Αποτυχία αποθήκευσης κατάστασης",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("gr");

  const t = (key: string) => translations[lang][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
